### ISSUE TITLE
linter: check that references are a list

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1027]
(derived from https://github.com/mandiant/capa-rules/pull/557)

The linter should check that `rule.meta.references` is a list of strings to ensure consistency in the rules.

**Comment by mike-hunhoff** [comment]
should list type be enforced for the `author` field as well? we currently see both string and list types for this field.

**Comment by williballenthin** [comment]
hmm seems like a good idea. should rename the field “authors” then?
