### ISSUE TITLE
display dotnet token in capa output

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1053]
I believe we intended to display the dotnet token but the output currently displays dotnet table name  + index. maybe an erroneous `str` somewhere?

![175386235-7b27fab6-8e6e-4d05-810a-1096fa2e09c7](https://user-images.githubusercontent.com/42192796/175563082-f8b5bdb6-7e76-412e-be32-810d67bf2bd9.png)

**Comment by williballenthin** [comment]
a few options:


### today
![image](https://user-images.githubusercontent.com/156560/176239717-028a426b-a193-4a14-b2eb-85d91c0aff61.png)


### colon separated
![image](https://user-images.githubusercontent.com/156560/176240478-d7e08c8c-150c-480d-b2ce-f69644828919.png)


### parenthesis
![image](https://user-images.githubusercontent.com/156560/176240584-ef3c9f95-5e40-4437-9407-d54bd227f35d.png)

**Comment by williballenthin** [comment]
the place to change is here:

![image](https://user-images.githubusercontent.com/156560/176241052-23ed65c3-3aa8-4401-92e3-808b2577ed53.png)

https://github.com/mandiant/capa/blob/3323d85067f735761a445e5a6a4245bac138917f/capa/render/verbose.py#L47

**Comment by mr-tz** [comment]
I like parenthesis but colon also works.
