### ISSUE TITLE
[Bug] - AttributeError 'capa.render.result_document' has no attribute 'convert_capabilities_to_result_document'

### ISSUE THREAD

**Issue by re-fox** [mandiant/capa#1071]
### Description
When using `capa_as_library`, error is raised on `convert_capabilities_to_result_document`

### Steps to Reproduce
A naive test case:
```python
>>> from scripts.capa_as_library import *
>>> results = capa_details('tests/data/mimikatz.exe_')
CB is None in graph building?!?! (0x41d286)
(fva: 0x0041d251 cbva: 0x0041d286)
FB is None in graph building!??!
..snipped...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "capa/scripts/capa_as_library.py", line 178, in capa_details
    doc = capa.render.result_document.convert_capabilities_to_result_document(meta, rules, capabilities)
AttributeError: module 'capa.render.result_document' has no attribute 'convert_capabilities_to_result_document'
```

**Expected behavior:**
Return dict of capa_output to caller

**Actual behavior:**
AttributeError is raised

### Versions
Build from latest `master`

### Additional Information
n/a

**Comment by williballenthin** [comment]
also, welcome back :-)

**Comment by doomedraven** [comment]
Hello all, i just builded from master, and also suffering the same

**Comment by doomedraven** [comment]
yes is what i just spot, that the code changes. thanks for update capa_as_library
