### ISSUE TITLE
thorough rule linting

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1076]
capa-rules CI is broken until v4 release due to running the rule set using the last major version v3 which has incompatible changes. therefore, we should do a local run of the linter with the `--thorough` flag.

**Comment by mr-tz** [comment]
running this now

**Comment by mr-tz** [comment]
better: now running in CI at https://github.com/mandiant/capa-rules/runs/7152547935?check_suite_focus=true

**Comment by mr-tz** [comment]
https://github.com/mandiant/capa-rules/issues/583

**Comment by mr-tz** [comment]
done via https://github.com/mandiant/capa-rules/issues/583
