### ISSUE TITLE
`invalid rule: feature format(dotnet) not supported for scope function`

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1089]
gives `invalid rule: feature format(dotnet) not supported for scope function` since format is not allowed except for file scope. should we make it global or add it to function and instruction scopes?

_Originally posted by @mr-tz in https://github.com/mandiant/capa-rules/pull/579#discussion_r913413005_

**Comment by williballenthin** [comment]
yes, lets definitely do this now that `format` is used to indicate dotnet (and soon, scripting languages)
