### ISSUE TITLE
Flare Capa & Flare Floss Dependency Issue

### ISSUE THREAD

**Issue by abaker2010** [mandiant/capa#1111]
I have been trying to install and use both Capa and Floss on my system, but there are many dependency issues that need to be resolved. Below I have marked the issues that need to be resolved, and the version differences. Thank you for all the hard work that you all have done on these programs! 

----------------------------------------------------------------
capa                               |  floss
----------------------------------------------------------------
funcy              1.16         |   funcy             1.17
pefile              2021.9.3 |   pefile            2022.5.30
tqdm              4.63.0     |   tqdm              4.64.0
viv-utils          0.6.11      |   viv-utils         0.7.5
vivisect           1.0.7       |   vivisect          1.0.8

**Comment by abaker2010** [comment]
This issue is for the release available via pip not for the current main branch. More of an informational comment instead of a true issue.

**Comment by mr-tz** [comment]
Thanks for the info. We'll have the new capa release with updated dependencies out soon.
A workaround to avoid future conflicts like this could be to use different virtual environments.
