### ISSUE TITLE
Suggest to loosen the dependency on halo

### ISSUE THREAD

**Issue by Agnes-U** [mandiant/capa#1126]
Hi, your project capa requires "halo==0.0.31" in its dependency. After analyzing the source code, we found that the following versions of halo can also be suitable without affecting your project, i.e., halo 0.0.30. Therefore, we suggest to loosen the dependency on halo from "halo==0.0.31" to "halo>=0.0.30,<=0.0.31" to avoid any possible conflict for importing more packages or for downstream projects that may use capa. 

May I pull a request to further loosen the dependency on halo?

By the way, could you please tell us whether such dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

<br />

----

We also give our detailed analysis as follows for your reference:

Your project capa directly uses 1 APIs from package halo.

```
halo.halo.Halo.__init__

```

Beginning from the 1 APIs above, 14 functions are then indirectly called, including 8 halo's internal APIs and 6 outsider APIs. The specific call graph is listed as follows (neglecting some repeated function occurrences). 

```
[/mandiant/capa]
+--halo.halo.Halo.__init__
|      +--halo._utils.get_environment
|      |      +--IPython.get_ipython
|      +--halo.halo.Halo.stop
|      |      +--halo.halo.Halo.clear
|      |      |      +--halo.halo.Halo._write
|      |      |      |      +--halo.halo.Halo._check_stream
|      |      +--halo.halo.Halo._show_cursor
|      |      |      +--halo.halo.Halo._check_stream
|      |      |      +--halo.cursor.show
|      |      |      |      +--halo.cursor._CursorInfo.__init__
|      |      |      |      +--ctypes.windll.kernel32.GetStdHandle
|      |      |      |      +--ctypes.windll.kernel32.GetConsoleCursorInfo
|      |      |      |      +--ctypes.windll.kernel32.SetConsoleCursorInfo
|      |      |      |      +--ctypes.byref
|      +--IPython.get_ipython
|      +--atexit.register
```

We scan halo's versions and observe that during its evolution between any version from [0.0.30] and 0.0.31, the changing functions (diffs being listed below) have none intersection with any function or API we mentioned above (either directly or indirectly called by this project).
```
diff: 0.0.31(original) 0.0.30
[](no clear difference between the source codes of two versions)

```

As for other packages, the APIs of IPython, atexit and ctypes are called by halo in the call graph and the dependencies on these packages also stay the same in our suggested versions, thus avoiding any outside conflict.

Therefore, we believe that it is quite safe to loose your dependency on halo from "halo==0.0.31" to "halo>=0.0.30,<=0.0.31". This will improve the applicability of capa and reduce the possibility of any further dependency conflict with other projects.

**Comment by williballenthin** [comment]
thanks for the suggestion, but at the time, we're happy with our approach to versioning.
