### ISSUE TITLE
dnlib dependancy in capa/features/address.py

### ISSUE THREAD

**Issue by kaze0mx** [mandiant/capa#1139]
### Context
First of all, I'm a big fan of Capa, thank your for this great tool! I have been successfully integrating Capa into [Malcat](https://malcat.fr) (you can test the capa integration in the free version if you're curious) for some time now. I use my own main script to list matching rules and my own extractor (using Malcat's python bindings). So basically I just keep the engine and the rules and discard evtg else. Integration was pretty easy and clean until now because the engine/features are very well detached from the extractors (great job guys !).

### Problem

In capa 4.0, the separation between extractor and features has a tiny flaw: there is a dnlib dependancy in `capa/features/address.py`:

```python
[capa/features/address.py](https://github.com/mandiant/capa/compare/v3.2.0...master#diff-0727ca1e119ebd353a0204473ea5b404b0e0d60d58d777d6d81af2ad75af8732)
@@ -0,0 +1,117 @@
import abc

from dncil.clr.token import Token    # <-- there
```

And this is used in these two classes:

```python
class DNTokenAddress(Address):
    """a .NET token"""

    def __init__(self, token: Token):
        self.token = token
    # ...


class DNTokenOffsetAddress(Address):
    """an offset into an object specified by a .NET token"""

    def __init__(self, token: Token, offset: int):
        assert offset >= 0
        self.token = token
        self.offset = offset
    # ...
```

The use of dnlib is specific to the current dnlib-based extractor, another extractor could use another library. In fact, I have my own dotnet parser and my extractor doesn't need dnlib at all. And that's unfortunate since only the `token.value` seems to be used there, so why not store directly the token value as `int`?  In fact, I made the change in the v4.0 branch and it seems to have no impact at all.

Of course I could create a parallel branch with the `dncil.clr.token.Token`->`int` change and always rebase when integrating capa (that's what I'm doing right now), but I find it unfortunate that the clean features/extractors separation is gone because of this small detail. 

If you want, I could submit a PR where `int` is used there instead of `dncil.clr.token.Token`.

**Comment by mr-tz** [comment]
Thanks a lot for the feedback and the issue details! It's always exciting to see how other projects leverage our tools.

Your points make a lot of sense and we really strive to keep the components independent. The `Token` contains some additional properties, but I'm sure we can figure out a good solution. Let's wait for @mike-hunhoff's comment and then we're happy to accept a PR :)

**Comment by mike-hunhoff** [comment]
Thank you again for the feedback and details! The referenced line imports the `Token` class from [dncil](https://github.com/mandiant/dncil), a Python library (with no dependencies) that we developed to disassemble CIL instructions. capa's .NET feature extractor does not have a [dnlib](https://github.com/0xd4d/dnlib) dependency as we are able to emit features using only Python with the help of dncil and [dnfile](https://github.com/malwarefrank/dnfile), a Python library that parses .NET metadata.

That being said, I agree we should keep components of capa independent whenever possible. It would be great if you could open a PR with your changes - I don't see a reason why we can't remove the use of `Token` as long as our tests pass post change.

**Comment by kaze0mx** [comment]
Sorry I was in vacations and did not have time to clean my changes & push. Thanks  @mr-tz!

**Comment by mr-tz** [comment]
No worries. Hope this works well for you now!
