### ISSUE TITLE
update deps for python 3.11

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1192]
things like python-flirt need to be built for python 3.11 and distributed via pypi

**Comment by williballenthin** [comment]
see #1191 for update to CI for python 3.11

**Comment by kastonework** [comment]
Eagerly watching this :). It's a blocker for us to move to Python 3.11.

**Comment by williballenthin** [comment]
ack :-)

we have some dependencies written in rust, so needed to get that tooling updated and build those wheels. i'll look into this now that 3.11 has settled a bit.

**Comment by kastonework** [comment]
Thx! In the meantime I'll look at our own Rust+PyO3 libs...

**Comment by williballenthin** [comment]
```
ERROR: Could not find a version that satisfies the requirement python-flirt==0.7.0; extra == "flirt" (from viv-utils[flirt]) (from versions: none)
ERROR: No matching distribution found for python-flirt==0.7.0; extra == "flirt"
```

**Comment by williballenthin** [comment]
for the flirt dependency, (windows, linux) x (3.7-3.11) are building in github actions. i'm having trouble getting macos working. will continue, but its tedious.

**Comment by williballenthin** [comment]
https://pypi.org/project/python-flirt/0.8.4/

**Comment by williballenthin** [comment]
https://pypi.org/project/viv-utils/0.7.6/

**Comment by williballenthin** [comment]
working now https://github.com/mandiant/capa/actions/runs/3685691874

ready for merge
