### ISSUE TITLE
Cannot load capa rules from IDA7.5

### ISSUE THREAD

**Issue by hpvip161** [mandiant/capa#1202]
Hello everyone

I use Ida 7.5 sp3 with python 3.8 but i cannot load capa-rules to analysis. Error isbelow

![capa-error](https://user-images.githubusercontent.com/21293793/202070980-a778593f-f444-49b1-95c5-fcd269a1dcb2.jpg)

I tried capa-rules older version v4 and it doesn't show error but no result after analysis.
I have no way to fix the error !!! pLs help me

**Comment by mr-tz** [comment]
So, the `v4` rules load successfully but there are no hits?
Could you share a screenshot of the plugin and the output window from IDA?

**Comment by mr-tz** [comment]
Please try again with the respective rule release available at https://github.com/mandiant/capa-rules/releases.
Feel free to reopen this if you still have issues.
