### ISSUE TITLE
Bug in import-to-ida.py

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/capa#1204]
Hi @williballenthin 
Please fix 2 bugs in import-to-ida.py file:
1. https://github.com/mandiant/capa/blob/5196caabb53c9ee3a4565d345f40e499b2b367e9/scripts/import-to-ida.py#L76
Change to: 
b = idc.retrieve_input_file_md5().hex()
2. https://github.com/mandiant/capa/blob/5196caabb53c9ee3a4565d345f40e499b2b367e9/scripts/import-to-ida.py#L54
Change to:
```
    if len(existing) > 0:
        new = existing + "\n" + cmt
    else:
        new = cmt
```
To avoid existing comment is empty (blank), capa comment set will have a blank line on top
Thank and brgds
TQN

**Comment by williballenthin** [comment]
can you clarify the difference between `GetInputFileMD5` and `retrieve_input_file_md5`? the first one is documented on the website (https://www.hex-rays.com/products/ida/support/idapython_docs/idautils.html#idautils.GetInputFileMD5) so i have a small preference for it. does it not work in some cases?

**Comment by williballenthin** [comment]
ah the second function was moved to `ida_nalt.retrieve_input_file_md5` which i like even better
