### ISSUE TITLE
perf: consider putting all rules into a single file to reduce IO

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1212]
it can take a little while for capa to begin analyzing, because it has to load rules, signatures, etc.
we currently have 700+ rules, which i suspect might result in a lot of IO.
we should investigate how much of the loading time can be attributed to rule loading IO, and if the load time can be improved by optimizing the rule loading.
for example, perhaps we could support a zip archive of rules that's read into memory once, versus 700+ seek&read operations.

**Comment by williballenthin** [comment]
on my flimsy codespace (2 core/4gb ram) loading rules takes 1 second:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/156560/206202318-e8bebed9-c8e1-4866-8715-f2595bba0846.png">

total runtime against PMA 01-01 is 12s:
<img width="110" alt="image" src="https://user-images.githubusercontent.com/156560/206202484-7a440839-dca9-41f6-a480-2e75609ff44b.png">

so if we made this instantaneous, we'd get an 8% improvement for simple samples.

**Comment by williballenthin** [comment]
benchmarking the various parts of rule loading:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/156560/206204143-ff0ea46d-f075-4033-b810-020922c9fbb7.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/156560/206204207-8ee06844-62f8-4f20-be9c-36e88749aba9.png">

it takes a small amount of time to read the rule content and quite a bit of time to parse and validate the content. so, this proposal won't really address any performance issue related to rule loading.

**Comment by mr-tz** [comment]
Reopening to reconsider storing/loading the serialized RuleSet.

**Comment by williballenthin** [comment]
we've been discussing the strategy of caching rulesets to improve the startup time of capa.

we currently think that capa spends around five seconds loading rules before analyzing a sample. most of this time is validating rules and statements; this is a CPU task, not an IO task. we note that, most of the time, capa rules don't change from invocation to invocation.

therefore, we hypothesize that introducing a persistent cache of the validated ruleset can speedup capa by 4-5 seconds.

the design might look something like this:
  1. check if cache exists. if not, load rules as normal.
  2. when rules have been validated and the ruleset object is created, write the cache to disk.
  3. the cache can be written into the temp dir or similar. it should not be a problem for the cache to be deleted.
  4. the cache is a pickled representation of the ruleset. its probably 1-2 MB in size. binary format. loading this must be fast.
  5. when the cache is used, capa should validate that the cache matches the ruleset on disk. it might do this by hashing the rule content and comparing with a hash embedded in the cache. we want to avoid any cache invalidation problems.
  
we expect the hit rate on the cache should be pretty high because we don't think that many capa users often modify their rules. for example, the standalone capa.exe will always use the embedded rules (unless overridden) so we could distribute a pre-built cache for capa.exe that benefits most users.

**Comment by mr-tz** [comment]
Pickle is the easiest option vs. creating a custom JSON export format (likely several hundret LOC) for all objects embedded in a RuleSet.

Next steps:
- [ ] Sketch out source implementation
  - [ ] where does the cache reside? Options: tmp or cache special directories, configurable via environment variable
- [ ] adjust standalone build

**Comment by williballenthin** [comment]
### cache file location

The cache file should not be stored alongside capa code nor capa rules (it should be basically impossible to accidentally share). Users shouldn't stumble across the file unless they go looking for it. If the file is deleted accidentally or by the OS to reclaim disk/memory, that's totally ok.

We should try to find existing work on the topic of cache files and follow conventions.

Best choices so far:
  - Linux: `$XDG_CACHE_HOME/capa/`
  - Windows: `%LOCALAPPDATA%\flare\capa\cache` ([ref](https://stackoverflow.com/a/49783629/87207))
  - MacOS: `~/Library/Caches/capa` ([ref](https://stackoverflow.com/a/5084892/87207))

**Comment by williballenthin** [comment]
### cache file format

`b"capa" + b"\x00\x00\x00\x01" + zlib(pickle(object))`

object looks like:
  - `id: str` hash of source data
  - `ruleset: capa.rules.RuleSet`

**Comment by williballenthin** [comment]
we'll need to build a tool to generate a cache file into a known location so that we can pre-build the cache file for the standalone binaries. 

the logic for using the cache file for standalone binaries should be fairly straightforward: if `-r` is not present, use the embedded cache file. in fact, we don't *really* need the rules to be embedded too, but i personally think its good for the source data to be around. 

building the cache in CI and adding it to the pyinstaller build will take a few minutes but *should* be pretty straightforward.

**Comment by mr-tz** [comment]
Should we also do this for the signatures/signature analyzer? That part also takes a couple of seconds and rules almost never change.

This may be done in `viv-utils`.

**Comment by williballenthin** [comment]
I don’t think this will work for the signatures because the marcher is implemented in Rust and therefore cannot be pickled. I’m still a bit surprised how slow the signature loading is, but in the past when I’ve studied it, I wasn’t able to find any obvious places to fix. Perhaps I should try again to save another few seconds. On Dec 22, 2022, at 6:26 PM, Moritz ***@***.***> wrote:﻿
Should we also do this for the signatures/signature analyzer? That part also takes a couple of seconds and rules almost never change.
This may be done in viv-utils.
