### ISSUE TITLE
capa is not able to analyze compiled openSLL

### ISSUE THREAD

**Issue by Ana06** [mandiant/capa#1221]
### Description

capa fails to detect ELF in the following compiled openSSL binary (64 bits ELF): https://www.virustotal.com/gui/file/d51ba239292fc90f8aff5941157d6ebc8c4ad18e1d40540ee789bf07bdf151d0

Removing the exclusion of `OS.SYSV` in `detect_elf_os()` fixes the issue.

### Steps to Reproduce

`capa d51ba239292fc90f8aff5941157d6ebc8c4ad18e1d40540ee789bf07bdf151d0`
![Screenshot 2022-12-07 at 18 29 33](https://user-images.githubusercontent.com/16052290/206249253-914a814a-7ae6-4d02-8259-dc0c2be3cd13.png)

**Expected behavior:**

capa analyzes the ELF sample.

**Actual behavior:**

Capa complains the OS is not supported.

### Versions

current master,  standalone tool

**Comment by williballenthin** [comment]
I've inspected the referenced file to try to determine how we can auto-detect that it targets Linux. I wasn't able to find any headers/metadata/etc. that specify Linux is the OS. There is an embedded function that shows the version information and references "linux", but I don't think this is something we can feasibly reason about:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/156560/206429664-529b6bfa-6afe-476a-83b1-1b7e7ad0d9f8.png">

There are various dependencies:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/156560/206429797-80b2db7e-5a23-4df5-a2f5-e59bad765e8e.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/156560/206429864-1957350e-94a2-46b9-90c8-504faca640b6.png">

 `libdl`, `libpthread`, and `libc` are all pretty standard, cross-platform libraries. however, the version references indicate the ABI/symbol version that's needed ([ref](https://stackoverflow.com/a/41093059)) and are restricted to `glibc`. According to the `glibc` [readme](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=README;hb=HEAD), this C library only targets GNU platforms, which are Linux and Hurd (uncommon in practice).

I wonder if its safe to assume glibc dependency -> Linux when we have no other hints?

**Comment by williballenthin** [comment]
here's what VT says:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/156560/206434223-d0af670e-c7f5-4904-b038-151236359156.png">

TRiD just barely says Linux. magic doesn't specify, just SYSV. DIE calls out the glibc dependency, but doesn't tie that to linux.

**Comment by williballenthin** [comment]
and [this 32-bit ELF](https://www.virustotal.com/gui/file/bf7a9c8bdfa6d47e01ad2b056264acc3fd90cf43fe0ed8deec93ab46b47d76cb/details) that i really can't tell, but suspect might be Hurd.

**Comment by williballenthin** [comment]
i will propose the following extension to the ELF OS detection algorithm:

```
if there is GLIBC symbol versioning:
  if arch != 32-bit x86: Linux
  if dynamic section references `libmachuser.so`: Hurd
  if dynamic section references `libhurduser.so`: Hurd
  if linker contains `ld-linux`: Linux
  if linker contains `/ld.so`: Hurd
  else: unknown
```
