### ISSUE TITLE
capa explorer: AttributeError: "CapaExplorerForm" object has no attribute "rules_cache" (load_capa_function_results)

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1246]
I think this is a result of removing the `None` initialization in #1235 

error occurs when you first open the plugin, rule generator tab, and select `Analyze`

**Comment by williballenthin** [comment]
ah ok that seems possible. probably i misunderstood where some of the properties were first assigned, so if its not in `__init__` then python would get unhappy. sorry for not catching this sooner!
