### ISSUE TITLE
Hello. I have to inform you that Windows blocks the download because it thinks its a virus. Also other Sandboxes indicate malicious behavior.

### ISSUE THREAD

**Issue by Tribiune** [mandiant/capa#1309]

**Comment by mr-tz** [comment]
Can you share more details on the blocking (virus warnings/details) or the sandbox information?

On VirusTotal I see two detections: https://www.virustotal.com/gui/file/c3b4764db35407ebbe852741e1aeb3d2dff4abb3bed651dc4681519ba404b5d4.

I can imagine that there could be hits in our binary on strings or other features we use to detect malicious functionality.

**Comment by Tribiune** [comment]
You can also run capa windows exe file on Triage sandbox and it indicates
it as bazarbackdoor.

Στις Πέμ, 9 Φεβ 2023, 10:43 π.μ. ο χρήστης Moritz ***@***.***>
έγραψε:

**Comment by williballenthin** [comment]
tria.ge report here shows that there's a yara hit for `BazarBackdoorVar3`. I don't know this rule and I can't find its source. There's a good chance they're matching on file strings, but I can't be sure.

https://tria.ge/230208-1za6zsgf6z/static1
