### ISSUE TITLE
Add additional metadata to functions and basic blocks in result layout

### ISSUE THREAD

**Issue by jconnor0426** [mandiant/capa#1325]
### Summary

In order to facilitate further analysis it would be helpful to include additional function and basic block metadata from the extractor in the result doc layout. Currently only the function address and basic block is included. 

Key metadata to add:
* function size
* Basic block size

Other helpful metadata:
* raw bytes of the function
* Raw bytes of the basic block 
* bytes of the function masked by the extractor for detection creation
* bytes of the function masked by the extractor for detection creation

### Motivation

Since CAPA analyzes files with vivisect and dncil, the details of a function are already captured. By exposing them in the result doc we can make follow on analysis to create YARA signatures for the functions or basic blocks much faster. In order to do so we need at least the size of the function/basic block along with the virtual address which we currently have. 

### Describe alternatives you've considered

This could be done in additional scripts, but I think the value of this approach is worth incorporating into the main .exe

**Comment by mr-tz** [comment]
Hey, that's an interesting idea. How would you use the function and block sizes to generate signatures?

As for the raw bytes, I think it'd be better to get this data via an external script using the match offsets from capa.
