### ISSUE TITLE
extract_insn_bytes_features in IDA extractor checks the instruction address for string, rather then the ref address

### ISSUE THREAD

**Issue by xusheng6** [mandiant/capa#1327]
https://github.com/mandiant/capa/blob/master/capa/features/extractors/ida/insn.py#L175

In comparison,

https://github.com/mandiant/capa/blob/master/capa/features/extractors/ida/insn.py#L193

**Comment by williballenthin** [comment]
i think this is explained by the comment in the following line at 176:

```py
            if not capa.features.extractors.ida.helpers.find_string_at(insn.ea):
                # don't extract byte features for obvious strings
                yield Bytes(extracted_bytes), ih.address
```

so, we aren't extracting bytes features when there's a string present, since we assume people would prefer to match on the string. this was added in #1298. does this makes sense to you?

**Comment by xusheng6** [comment]
Well, yes, but it is calling “find_string_at” on insn.ea, instead of ref.
And I suppose the behavior is to try to find a string on the bytes of the
instruction, which does not make sense to me.

**Comment by xusheng6** [comment]
You can check out the second code snippet I linked, which is at line 193.
And that seems to me to be calling find_string_at correctly.

**Comment by williballenthin** [comment]
ah, ok, thanks for the additional explanation. i'm following you now.

seems like an easy fix, though we should also add a test to show the bug and then that the fix works. thanks for reporting @xusheng6!
