### ISSUE TITLE
IDA Capa Explorer - plugin causes issues if running ida in cmd batch mode.

### ISSUE THREAD

**Issue by cjchristopher** [mandiant/capa#1331]
### Description

With the Capa Explorer plugin installed correctly (and working in IDA), causes issues running ida on the command line - as the plugin doesn't check if ida is being run in batch or gui mode - Qt errors get thrown and causes the analysis to lock up / never complete, presumably as it is trying to update/address GUI elements that don't exist.

### Steps to Reproduce

Install Capa Explorer as per repo instructions (verify it works correctly in GUI). Run a command line job (say via idat64) that possibly doesn't even involve the plugin (and indeed, never calls it)

**Expected behavior:**

Job to complete

**Actual behavior:**

Throws Qt errors.
"QPixmap: Must construct a QGuiApplication before a QPixmap"

### Versions

IDA Pro 7.6
capa 5.0.0
python 3.10
Win 10 Home

### Additional Information
N/A

**Comment by williballenthin** [comment]
interesting, I bet this has to do with trying to load the icon. 

perhaps we should update the following logic to not load capa explorer in headless mode:

https://github.com/mandiant/capa/blob/501e213dcec2e062648d282852fed0b6717915c6/capa/ida/plugin/__init__.py#L43-L50

**Comment by mike-hunhoff** [comment]
@cjchristopher I've opened a fix for this under #1341
