### ISSUE TITLE
check_segment_for_pe in IDA extractor does unnecessary search

### ISSUE THREAD

**Issue by xusheng6** [mandiant/capa#1333]
I think there is no need to push the next address into the todo list at https://github.com/mandiant/capa/blob/master/capa/features/extractors/ida/file.py#L64-L65, since we have already found all `mzx` at https://github.com/mandiant/capa/blob/master/capa/features/extractors/ida/file.py#L41-L44

**Comment by mike-hunhoff** [comment]
Nice catch @xusheng6 ! I've addressed this in #1344
