### ISSUE TITLE
lint python code with ruff

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1359]
we should investigate using [ruff](https://github.com/charliermarsh/ruff) for linting as well.

i was able to install and run it quickly. there are a number of things we'll have to tune, but it does identify a few legitimate issues that other linters have missed.

**Comment by ooprathamm** [comment]
Tried ruff locally, and it really is super fast!

what are we wishing for here -
1. migrating from pycodestyle -> ruff
2. having both the linters

**Comment by williballenthin** [comment]
since none of us have much experience with ruff, let’s add it in addition and have two linters.
