### ISSUE TITLE
ensure standalone binary can work without embedded cache

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1361]
The problem is that I am running the PyInstaller locally to test if the new binja backend works. If I run the PyInstaller command without generating the rule cache first. The generated executable will complain the rule cache is missing when I run it. Note, I added the above code snippet in the section `3. Compile binary using PyInstaller`

_Originally posted by @xusheng6 in https://github.com/mandiant/capa/pull/1343#discussion_r1126428957_

**Comment by s-ff** [comment]
@williballenthin @mr-tz do you think we can use [`exec_statement`](https://pyinstaller.org/en/stable/hooks.html#PyInstaller.utils.hooks.exec_statement) from `PyInstaller.utils.hooks` in to cache the ruleset (using `capa.rules.cache.cache_ruleset`) before proceeding to build the executable? Would that be optimal?

**Comment by williballenthin** [comment]
.github/workflows/build.yml:55 already builds the cache and embeds it into the standalone binary.

**Comment by williballenthin** [comment]
ah i see so move that configuration into the PyInstaller to ensure the step can't be missed. neat! 

yeah i think this is reasonable to try

**Comment by mr-tz** [comment]
nice, note the note:
> As of v5.0, usage of this function is discouraged in favour of the new [PyInstaller.isolated](https://pyinstaller.org/en/stable/hooks.html#module-PyInstaller.isolated) module.
