### ISSUE TITLE
run IDA tests headlessly

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1364]
it would be nice to invoke the capa tests under IDA without interacting with the IDA GUI. this would enable things like #1362 (run IDA tests in CI). the test runner inside IDA could emit the test results to a file specified via CLI and a wrapper script that invokes IDA might read and render this back to the user.

**Comment by williballenthin** [comment]
This technique is described by github here: https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-large-secrets

**Comment by williballenthin** [comment]
might be a pain to figure out how to install IDA headlessly in CI

**Comment by ggold7046** [comment]
Hi @williballenthin , could you please explain the above problem in detail. What is meant by headless IDA ?

**Comment by williballenthin** [comment]
I mean that we want to run IDA Pro in our CI/CD setup so that we can execute our test cases. Typically this program is run with a GUI so by “headless” I mean we need to control it without a display.

**Comment by ggold7046** [comment]
Can we use the free IDA version ? I don't have the PRO version though.

**Comment by williballenthin** [comment]
Unfortunately not because the free version doesn’t support scripting with Python. We’ll need to use one of our paid licenses for this, unless perhaps Hex-Rays donates a server license for us to use in CI/CD.

**Comment by williballenthin** [comment]
its a little tricky to invoke all the tests today, because they expect to be run against a bunch of different input samples and assert that features are extracted. we'll need to find a way to structure the tests such that they're easy to invoke in CI.

one way might be to only run the test cases that match the currently loaded sample, and skip the remainder. then the CI configuration can invoke the test runner script against each sample referenced in the tests. its a little configuration-heavy, but wouldn't require too many changes and does get the job done.

these changes would also support running Ghidra backend in CI more easily.

**Comment by williballenthin** [comment]
today we have [test_ida_features.py](https://github.com/mandiant/capa/blob/1336796/tests/test_ida_features.py).

this script is named like a pytest file; however, all the test cases inside are skipped because the tests don't actually run in pytest. this is ok. its just documentation.

the file expects to be executed as a script inside of IDA. when the current file MD5 matches the file used by a feature test, then the test is invoked (directly, as a function, not via pytest) and the result printed to stdout.

<img width="483" alt="image" src="https://github.com/mandiant/capa/assets/156560/68a1ab30-ff2a-4a95-aae2-be9ac3c429fe">

#1513 refines the test runner so that it can be invoked easily from the command line:

<img width="1336" alt="image" src="https://github.com/mandiant/capa/assets/156560/155d1de0-8987-4268-8394-af11961fbcb9">

**Comment by williballenthin** [comment]
our features tests currently reference the following files:

- "294b8d..."
- "64d9f"
- "7351f.elf"
- "773290..."
- "79abd..."
- "946a9..."
- "a1982..."
- "al-khaser x64"
- "c91887..."
- "kernel32-64"
- "kernel32"
- "mimikatz"
- "pma12-04"
- "pma16-01"

**Comment by williballenthin** [comment]
there are a handful of failing tests @mike-hunhoff 

```
FAIL: test_ida_features/pma12-04-file-characteristic(embedded pe)-True
Traceback (most recent call last):
  File "C:/Exclusions/code/capa/tests/test_ida_features.py", line 62, in test_ida_features
    fixtures.do_test_feature_presence(get_ida_extractor, sample, scope, feature, expected)
  File "C:\Exclusions/code/capa/tests\fixtures.py", line 1018, in do_test_feature_presence
    assert feature.evaluate(features) == expected, msg
AssertionError: characteristic(embedded pe) should be found in file

FAIL: test_ida_features/pma16-01-function=0x404356-os(windows)-True
Traceback (most recent call last):
  File "C:/Exclusions/code/capa/tests/test_ida_features.py", line 62, in test_ida_features
    fixtures.do_test_feature_presence(get_ida_extractor, sample, scope, feature, expected)
  File "C:\Exclusions/code/capa/tests\fixtures.py", line 1013, in do_test_feature_presence
    features = scope(extractor)
  File "C:\Exclusions/code/capa/tests\fixtures.py", line 486, in inner_function
    fh = get_function(extractor, va)
  File "C:\Exclusions/code/capa/tests\fixtures.py", line 395, in get_function
    raise ValueError("function not found")
ValueError: function not found


(...and a few others with the same failure: above function can't be found by IDA)
```
