### ISSUE TITLE
triage existing TODOs and schedule re-reviews

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1391]
> sidebar: i wish there was a way to tag fixes like this to be re-reviewed in 6 months or so. maybe we could introduce a convention like # TODO(2023-06): review mypy override and periodically grep the code for things to be re-assessed. thoughts @mr-tz @mike-hunhoff

cool, idea! I think we already have a few TODO places that can benefit from such an annotation (and regular check, which would be cool to flag via an Action or similar).

_Originally posted by @mr-tz in https://github.com/mandiant/capa/issues/1382#issuecomment-1477897568_

**Comment by mike-hunhoff** [comment]
I'd like to see these TODOs added as new issues with a `TODO` label or something similar. IMO this would make it easier to track. I briefly searched and found this interesting GH action: `https://github.com/marketplace/actions/track-todo-action` that will automatically create new issues when a PR is made containing new `TODO` comments. If we track issues with a `TODO` or similar label it should be straightforward to run a follow-up action to remind us about open TODOs.

**Comment by williballenthin** [comment]
we can use https://github.com/orsinium-labs/flake8-todos to ensure that inline `TODO` comments must reference a github issue URL. i sorta like this solution better because it doesn't rely on any state/integration with github directly.

**Comment by williballenthin** [comment]
added in ae10a2ea34a9cf08d30d80a1ae2675d0c26de5da in #1579
