### ISSUE TITLE
bn: test binja backend when invoking standalone capa.exe

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1446]
> I did not do the "test run with BN" as mentioned here: https://github.com/mandiant/capa/issues/1430#issuecomment-1500593410. I am not entirely sure what is the best way to organize the code. I saw there is already a capa test run action, but that one does not download and install BN. Not sure whether the binja test run should be part of it, or it should be part of the BN test process. @williballenthin Could I leave this for you?

_Originally posted by @xusheng6 in https://github.com/mandiant/capa/issues/1435#issuecomment-1501357817_

**Comment by Aayush-Goel-04** [comment]
@williballenthin , I would like to work on this.
I am thinking of creating a test in `test_main.py` to test standalone binja backend.

**Comment by williballenthin** [comment]
that should work, though the test should be skipped if BN is not installed, so you might want to refer to the code from here: https://github.com/mandiant/capa/blob/21c2705827df2ff1106c01768eb493e7d88dcf17/tests/test_binja_features.py#L15-L30).

you'll need to update here, too: https://github.com/mandiant/capa/blob/21c2705827df2ff1106c01768eb493e7d88dcf17/.github/workflows/tests.yml#L138

**Comment by williballenthin** [comment]
thanks for taking this on @Aayush-Goel-04
