### ISSUE TITLE
BN: use shared secret so tests always run?

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1452]
Tests always fail except for Willi? Can we add a shared secret used for testing?

**Comment by williballenthin** [comment]
the secret is available for this repo, not associated with my account. probably it only works if the PR is made from this repo to this repo (versus from fork mr-tz/capa to mandiant/capa). i dont think there are any settings we can change here regarding how the secret is shared, but im happy to be wrong.

**Comment by mr-tz** [comment]
Ah, yeah, that makes sense! Thanks for clarifying.
