### ISSUE TITLE
Can we please remove data submodule or at least encrypt test data?

### ISSUE THREAD

**Issue by isimsizolan** [mandiant/capa#1465]
I almost got fired today for accidently downloading malwares to my work computer :) I playing capa and enjoying capa source code on my work computer because my internal access to work repos not yet ready and i had lots of free time. Then i want to check out rules so i initiate submodule load with single command, not knowing there was another submodule in test which has test malware. Sophos's interceptX goes crazy and marked incident as outbreak and took ownership of the repo so i cant delete them either. In a matter of seconds, i was a fresh employee who just downloaded 100's of malware to some fintech software company domain. Couple of minutes i decided to wait silently to be get fired or try priviledge escalation so i can delete malwares at least and get fired :)

Can we at least zip them?

**Comment by williballenthin** [comment]
thanks for sharing the experience you had - we've been aware that the testfiles repo has malware and that users should be careful with this.

today, our documentation describes that users need to exercise caution when doing a recursive submodule checkout:
![image](https://user-images.githubusercontent.com/156560/235632699-7dab16ba-f165-4711-a289-866195340e9c.png)

how do you think we could update this documentation to make it easier to understand and avoid this scenario?

**Comment by isimsizolan** [comment]
the story was for fun, still defacto rule is to zip malware samples with password, commonly 'infected', this way you will protect users whom did not read documentation like me and anyone trying to unzip the malware samples know exactly what she is doing.

**Comment by williballenthin** [comment]
we're not going to change the setup of the testfiles repo today, given that the contents are well documented to contain malware and the workflow of doing a recursive submodule checkout is uncommon among our users. im very sympathetic to your story, as it sounds like something that would happen to me too!
