### ISSUE TITLE
find interesting dynamic analysis traces

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1498]
want to see some examples of things like:

  - file write
  - registry write
  - file read (such as browser cookies.db)
  - process injection
  - big tree of processes and subprocesses

lets link to the sample hash and URL of the sandbox run here. maybe also attach trace file if its available.

**Comment by yelhamer** [comment]
I think the objective with this is to cover as many types of samples as possible: 

- different formats: ELF, PE, .NET, other? 👀
- samples with network traffic including different protocols and ports, as well as interesting captured traffic.
- samples that do file/registry access
- samples that use threading
- samples with interesting api/file call sequencing
- samples that execute interesting powershell/bash/else commands
- packed/obfuscated samples (pretty important)
- other recommendations?

**Comment by xusheng6** [comment]
Is capa eyeing the capacity to detect insetting events based on an execution trace? Or this is just looking for patterns during static analysis

**Comment by williballenthin** [comment]
@yelhamer is our Google Summer of Code contributor who is working to add support for dynamic analysis traces to capa. For example, providing an API trace emitted by the CAPE sandbox and letting capa recognize the behaviors and explaining the relevant events.

**Comment by yelhamer** [comment]
@xusheng6 this will be based on the execution trace provided by the supported sandboxes. for now, we're fixated on adding support for the cape sandbox and are basing the design on it, support for other sandboxes can then ensue.

you can check discussion https://github.com/mandiant/capa/discussions/1517 (specifically Willi's last comment) to see where things are at currently. also, please feel free to share any ideas you might have!

**Comment by yelhamer** [comment]
Sample 1: 19ee7b4a940eb1bd1c824ff02ac062e75ee9fa7331e9daf47da2493a17abf875
Format: PE .NET
Obfuscation: .NET base64 and xor obfuscation
links: [MalwareBazaar](https://bazaar.abuse.ch/sample/19ee7b4a940eb1bd1c824ff02ac062e75ee9fa7331e9daf47da2493a17abf875/), [CAPE](https://capesandbox.com/analysis/395844/), [VirusTotal](https://www.virustotal.com/gui/file/19ee7b4a940eb1bd1c824ff02ac062e75ee9fa7331e9daf47da2493a17abf875/behavior)

Reason to include: Capa reports 4 low-severity mitre att&ck techniques, while VMRay reports 13.

**Comment by xusheng6** [comment]
> @yelhamer is our Google Summer of Code contributor who is working to add support for dynamic analysis traces to capa. For example, providing an API trace emitted by the CAPE sandbox and letting capa recognize the behaviors and explaining the relevant events.

@williballenthin @yelhamer Really excited to learn that CAPA is adding the capacity to work with dynamic traces. I will add some thoughts in #1517

**Comment by mr-tz** [comment]
> Sample 1: 19ee7b4a940eb1bd1c824ff02ac062e75ee9fa7331e9daf47da2493a17abf875

As a first test sample .NET may be tough because the decompiled code and API trace differ quite a bit (.NET API vs. low-level Windows API). 

I'd probably start with an (unpacked) native binary. This would allow us to compare static and dynamic capa results more easily as well.

**Comment by yelhamer** [comment]
Sample 2: SmokeLoader
SHA256: c0832b1008aa0fc828654f9762e37bda019080cbdd92bd2453a05cfb3b79abb3
Format: Native PE
Links: [CAPE](https://capesandbox.com/analysis/396292/), [VT](https://www.virustotal.com/gui/file/c0832b1008aa0fc828654f9762e37bda019080cbdd92bd2453a05cfb3b79abb3/behavior), [Bazaar](https://bazaar.abuse.ch/sample/c0832b1008aa0fc828654f9762e37bda019080cbdd92bd2453a05cfb3b79abb3/)
Reasons to include: the binary uses several dynamically loaded DLLs to implement several functionalities that are undetected by Capa, namely: AV evasion, Sandbox/Virtualization detection, establishes network connections, etc.

**Comment by williballenthin** [comment]
AVAST has published a large, open source collection of CAPE sandbox runs here:
https://github.com/avast/avast-ctu-cape-dataset

there are 48,976 sandbox reports, 14GB compressed, probably 150GB decompressed.

when possible, we should pick traces from this dataset because the data is open source so we can copy it into capa and/or testfiles without concern.

**Comment by yelhamer** [comment]
Sample 3: QakBot
SHA256: 4a5d62f144eb33a92670f3daf285e8de70a6d2074fc1e4e1c4238be95310f221
Format: Native PE
Download trace: [0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.zip](https://github.com/mandiant/capa/files/11789481/0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.zip)

**Comment by mr-tz** [comment]
@yelhamer, can you share 1-2 CAPE JSON reports plus their respective files. I cannot find 4a5d62f144eb33a92670f3daf285e8de70a6d2074fc1e4e1c4238be95310f221 / 0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.

**Comment by mr-tz** [comment]
done as part of v7
