### ISSUE TITLE
ghidra: extend main.py to detect Ghidra runtime

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1506]

**Comment by colton-gabertan** [comment]
Please see [backend-ghidra/main.py](https://github.com/mandiant/capa/blob/backend-ghidra/capa/main.py) for review. Future updates will be submitted to close issues properly.

**Comment by mike-hunhoff** [comment]
What you have looks good so far. Have you tested `main.py` from both the script manager and Ghidra headless mode?

**Comment by colton-gabertan** [comment]
> What you have looks good so far. Have you tested `main.py` from both the script manager and Ghidra headless mode?

The runtime detection seems to be working from both the script manager and the headless mode :). Please let me know if it's alright to close this issue.
