### ISSUE TITLE
ghidra: global features extraction

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1507]

**Comment by colton-gabertan** [comment]
Please see [backend-ghidra/global_.py](https://github.com/mandiant/capa/blob/a7988a6e7868258db2c576f858f5c8ba91e94020/capa/features/extractors/ghidra/global_.py) for review. Future updates will be marked properly to close issues.

**Comment by mike-hunhoff** [comment]
I'm curious as to why the following line is needed:

https://github.com/mandiant/capa/blob/a7988a6e7868258db2c576f858f5c8ba91e94020/capa/features/extractors/ghidra/global_.py#L11

As it appears to only be used to grab another reference to `currentProgram`?

https://github.com/mandiant/capa/blob/a7988a6e7868258db2c576f858f5c8ba91e94020/capa/features/extractors/ghidra/global_.py#L20

Ghidrathon should globally expose `currentProgram` alongside the FlatProgramAPI and its APIs (see https://github.com/mandiant/Ghidrathon/blob/main/ghidra_scripts/ghidrathon_example.py).

If this isn't the case we should address this in Ghidrathon. We want the Ghidrathon experience to be as close as possible to the native Ghidra scripting experience 😄

**Comment by mr-tz** [comment]
side bar: I feel like creating a project development branch and submitting PRs into it makes for a better workflow to follow along and provide reviews

**Comment by colton-gabertan** [comment]
> 

Apologies for that, I was originally working in my fork before I got the permissions to start working out of the main one
