### ISSUE TITLE
use pathlib.Path to represent file system paths instead of strings 

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1534]
throughout the codebase, replace string type variables with pathlib.Path type variables that represent file system paths. these objects have convenient methods/properties for common operations, as well as make clear how the data should be used (as a file system path, not a string to display to the user, or whatever).

**Comment by williballenthin** [comment]
@Aayush-Goel-04 are you interested in taking a stab at this? we'll want to replace any uses of os.path with pathlib.

**Comment by Aayush-Goel-04** [comment]
Yes, will give it a try.
Thanks @williballenthin

**Comment by Aayush-Goel-04** [comment]
@williballenthin 
Should I replace `os.remove(path)` with `path.unlink()` or make it `os.remove(str(path))` if` path` is `pathlib.Path` type variable

**Comment by williballenthin** [comment]
yeah let's prefer to use pathlib where possible, so that means path.unlink.

**Comment by Aayush-Goel-04** [comment]
@williballenthin 
In capa/main should function like get_rules(rule_paths) / get_signatures(sigs_path) recieve paths of type strings, or pathlib.Path.
Currently it is passed directly as type strings from args.rules and args.signatures

**Comment by williballenthin** [comment]
we should try to work with pathlib as much as possible.

we'll want to convert from str to pathlib.Path as soon as possible, and convert back to str only when we're about to render it to a user.

**Comment by Aayush-Goel-04** [comment]
Hey @williballenthin ,
I was planning to change type from str to path for rules, signatures & samples in `install common args`. 
What should I change their default values to ?

**Comment by williballenthin** [comment]
please propose something that makes sense to you and we can discuss. i think it just needs to be sensible; i don't think we have to be too strict with these types, but it's something to try for. 

for example, it's ok to use str with argparse right when the CLI args come in. we'd just want to convert to pathlib before any other code works with the data. 

hope that makes sense, happy to talk further. but remember, i trust you to figure out a good solution :-)

**Comment by mr-tz** [comment]
Thanks, @Aayush-Goel-04
