### ISSUE TITLE
explore CAPE sandbox report file format

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1535]
use this issue to describe the interesting parts of the CAPE sandbox report file format. describe how we could extract data into capa-level features.

**Comment by williballenthin** [comment]
using 0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.json from the avast repo

<img width="791" alt="image" src="https://github.com/mandiant/capa/assets/156560/36beed67-4439-411d-8c1c-e07b56ac6c61">


general layout like this:

<img width="821" alt="image" src="https://github.com/mandiant/capa/assets/156560/16832a2a-1ed2-4775-917a-1e57f9c937a9">

`behavior.processes[].calls[]` has the API trace:

<img width="649" alt="image" src="https://github.com/mandiant/capa/assets/156560/e23601a4-02d0-47a4-8b15-e009344c6c12">

from this we can extract:

  - PID
  - TID
  - API trace:
    - API name
    - return value
    - arguments
      - value
      - name

**Comment by williballenthin** [comment]
[0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.zip](https://github.com/mandiant/capa/files/11722792/0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.zip)

**Comment by yelhamer** [comment]
### extracted features and the associated report locations:

- **api**: the call trace for each process
- **strings**: strings report section, api arguments, CAPE.config, yara matches (if they include strings), environ section of the process tree, signatures section.
- **numbers**: api arguments.
- **bytes**: yara matches (if they include bytes).
- **network**: network section and pcap files parsing.
- **imports/exports**: static section.
- **section names**: static section.
- **commands**: commands section, the environ field of the process tree section.
-  **files**: the {create, read, deleted} files section.
- **registry keys**: the {create, read, deleted} registry keys section.
- **services**: the {create, started} services section.

**Comment by mr-tz** [comment]
The `info.version` field lists the CAPE version, e.g. `2.2-CAPE` that we currently use from the AVAST database.
We should ensure that this is what we expect as I've noticed small differences, e.g. to `2.4-CAPE` (here regarding how imports are organized).

**Comment by yelhamer** [comment]
especially once we've added the call scope. once that has been added we should make sure the cape version being used has the msdn names (not the legacy ones).

**Comment by doomedraven** [comment]
yes 2.2 and 2.4 doesn't have nothing big in changes. https://github.com/kevoreilly/CAPEv2/blob/master/changelog.md#2422023-cape-24--edition
