### ISSUE TITLE
update main logic to recognize CAPE analysis reports and invoke the right extractor

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1541]
when capa encounters a CAPE dynamic analysis report, it should recognize the file format and enter "dynamic analysis flavor" mode. it should load the appropriate feature extractor and invoke it such that capa can recognize the processes, threads, etc. 

this includes adding parallel logic around here: https://github.com/mandiant/capa/blob/2d7e20f5325dc61fd6c38500de5722d2707d7543/capa/main.py#L119-L242
that walks the dynamic flavor scopes and merges the features appropriately.

**Comment by yelhamer** [comment]
Addressed in #1644
