### ISSUE TITLE
website: pick tech stack

### ISSUE THREAD

**Issue by wballenthin** [mandiant/capa#1552]
things like:

- javascript or typescript?
- are we using a  compiler/bundler like webpack?
- how are we handling dependencies? with npm?
- how are we building the static assets? by hand, or with something like hugo?
- etc.

some of those dont have to be decided immediately, but we should be thinking about the decisions and making sure everyone is in agreement.

notably, we want to be sure the tech stack is reasonably easy to understand, so that other people can contribute to and maintain the website, if necessary.

**Comment by wballenthin** [comment]
i think using something like hugo or jekyll to translate from markdown and other source into a static website is a reasonable place to start. it would provide a framework to do the operation: for each capa rule, generate a page with a given URL and rich content.

open to other options too, im just a little familiar with the ones above and know that they're well supported.

**Comment by DeeyaSingh** [comment]
The attached document outlines the proposed tech stack, which includes the technologies, frameworks, and tools that I believe would be suitable for the project.
https://docs.google.com/document/d/1qhkEiGugjQ_mvuXZFEi11JRBIQl8vLmvaIrh5Zh1DbE/edit

**Comment by wballenthin** [comment]
@DeeyaSingh the tech stack proposal looks good! please proceed with the technologies listed here.
