### ISSUE TITLE
website: implement rule list page

### ISSUE THREAD

**Issue by ghost** [mandiant/capa#1556]

**Comment by DeeyaSingh** [comment]
Rule list page: https://deeyasingh.github.io/rule.html

The rule view page effectively reads and interprets YAML files. The page utilizes JavaScript and the library js-yaml to parse these YAML files, transforming their content into a JavaScript object.

Each rule is then dynamically rendered into a visually appealing and easy-to-understand rule card, offering an encapsulated view of individual rule information directly to the user.

**Comment by mr-tz** [comment]
Cool, I think the features should be shown as raw yml text instead as a parsed JSON.

**Comment by DeeyaSingh** [comment]
@mr-tz I've updated the features to be displayed in YAML format instead of parsed JSON. Could you take a look and let me know if this looks better?

**Comment by mr-tz** [comment]
Perfect, that looks great.
