### ISSUE TITLE
website: implement search rules functionality

### ISSUE THREAD

**Issue by ghost** [mandiant/capa#1557]

**Comment by williballenthin** [comment]
this is a good first implementation. its fast and effective.

we should also add the ability to search by:
  - authors
  - rule name
  - really, any of the metadata fields
  - rule content/features

and these searches should support both exact match and also substring match (like a part of the rule name).

it might be nice too to show the results as users are typing, assuming the performance is good enough.

**Comment by williballenthin** [comment]
this looks like a pretty nice library for searching static content, like we need for the capa website: https://pagefind.app/

**Comment by mr-tz** [comment]
Could also be helpful to inspect the FakeNet-NG report website tech stack (https://github.com/mandiant/flare-fakenet-ng/pull/163/files).
