### ISSUE TITLE
ida-explorer: use IDA API bin_search not find_binary

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1606]
https://github.com/mandiant/capa/blob/430f9da449cbd2c7142594f3bcf370cbcfee37d8/capa/features/extractors/ida/helpers.py#L31

**Comment by tehami02** [comment]
Can I work on this issue. Please assign me.

**Comment by williballenthin** [comment]
sure, it would be great to have your help.

to confirm, do you have a copy of IDA Pro that can run the capa explorer plugin? if not, it will be difficult to develop the changes and confirm they work.

**Comment by s-ff** [comment]
Hi @williballenthin 

I noticed this issue has been inactive for some time. Could you please reassign it to me? I'd like to push a fix.

Cheers.

**Comment by tehami02** [comment]
@williballenthin Sorry for late reply, actually I dont have IDA Pro, so you can assign this issue to other dev.
