### ISSUE TITLE
elf: implement file export name extractor

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1607]
https://github.com/mandiant/capa/blob/430f9da449cbd2c7142594f3bcf370cbcfee37d8/capa/features/extractors/elffile.py#L88

**Comment by Aayush-Goel-04** [comment]
I investigated ways to distinguish between import and export symbols. The current implementation identifies symbols as imports solely based on their type and name. However, after careful analysis, I found that the `st_shndx` field in the symbol entry plays a critical role in differentiating between imports and exports. If `symbol.entry.st_shndx = SHN_UNDEF (0x00)`, it signifies that the symbol is not defined within the ELF file, making it an import. On the other hand, the `st_shndx` field of export symbols points to the section index of the section where the symbol is defined.

The current `extract_file_export_names` extracts both import and export name from `.dynsym` and `.symtab`.  We should consider incorporating the st_shndx field check to accurately identify import and export symbols.

@williballenthin what are your thoughts

**Comment by williballenthin** [comment]
great find and excellent explanation. do you have any references to the specifications that support these conclusions? it would be great to link to them in the code. 

how do you think we should proceed? would you like to propose some updates to the code?

**Comment by williballenthin** [comment]
this article is very wordy but provides nice clear definitions at the bottom:

http://www.m4b.io/elf/export/binary/analysis/2015/05/25/what-is-an-elf-export.html

it's generally consistent with what you posted @Aayush-Goel-04 though it describes a few edge cases. seems like it shouldn't be too hard to handle.

**Comment by Aayush-Goel-04** [comment]
I was looking at the same paper 
https://stackoverflow.com/questions/12666253/elf-imports-and-exports
https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter6-79797.html#chapter6-tbl-21:~:text=bytes%20are%20required.-,SHN_UNDEF,-This%20section%20table

**Comment by Aayush-Goel-04** [comment]
@williballenthin I think we should look for export symbols in `section.name == .dynsym` rather than looking at all symbols for `isinstance(section, SymbolTableSection)`. I am not sure if we should also look at .symtab section name . Can you shed some light here.

**Comment by Aayush-Goel-04** [comment]
@williballenthin , Since #1608 is closely related to this I will also get that done as well.

**Comment by williballenthin** [comment]
i'm willing to go with your recommendation, especially if we can provide references to specifications or example files (for any edge cases we find). i don't have any particular knowledge of the ELF format, so i trust what you learn. 

if you need an opinion on which strategy to use, i'm happy to discuss, though i'd appreciate a bit of detail around what you've considered so far.
