### ISSUE TITLE
freeze: extend format to enable storage of dynamic reports

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1614]
from here: https://github.com/mandiant/capa/pull/1612#discussion_r1258122204

ideally we don't want to change the 8-byte static magic header ("capa0000"). today, the version field is embedded within the JSON data. this means we need to be able to decode the JSON before we know the version, which would inform how we parse the rest of the report.

perhaps we can parse just the version field from the report, then when we know the version == 3, then we can inspect a "flavor" field that specifies if the report is static or dynamic, and then parse the full report?

@yelhamer

**Comment by williballenthin** [comment]
while we could try to support prior versions, i think this will require a lot of code and testing and its unlikely that many people will use it (im not sure if anyone actually uses freeze very heavily). so until we hear otherwise, i think we should not worry about backwards compatibility.

so, we *could* make any arbitrary changes to the format that we want.

imagining a magic/file database, i'd prefer that the first 8 bytes identify the relevant application ("capa") and the remainder of the format be independent. otherwise that database would have to have two entries for capa, or a 7 byte value, which is ugly :-)

furthermore, if we start overriding that byte value, then we may continue to be tempted to do the same again in the future, and now there are many potential values to handle. i'd rather we use the magic field to indicate the program, the version field to indicate the format version, and a flavor field to indicate the interpretation. future versions can extend this if necessary.

**Comment by yelhamer** [comment]
closed in #1612
