### ISSUE TITLE
dynamic: find correct base address used at runtime

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1618]
https://github.com/mandiant/capa/blob/d29e7140b69245753714729391944ae95da68d75/capa/features/extractors/cape/thread.py#L43

**Comment by williballenthin** [comment]
we don't display or use these addresses today, so closing this out as not-needed.

if we want to correlate an API call with the source binary, this would be useful.

unfortunately, the base addresses of loaded modules are not reliably captured by CAPE, so this won't always be possible.
e.g. in `0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82` there is:

```json
{
  "timestamp": "2021-01-28 02:14:04,728",
  "thread_id": "3064",
  "caller": "0x77501fd7",
  "parentcaller": "0x744f7ec1",
  "category": "system",
  "api": "LdrGetProcedureAddress",
  "status": true,
  "return": "0x00000000",
  "arguments": [
    {
      "name": "ModuleName",
      "value": "WINSPOOL.DRV"
    },
    {
      "name": "ModuleHandle",
      "value": "0x744e0000"
    },
    {
      "name": "FunctionName",
      "value": "AddPrinterConnectionW"
    },
    {
      "name": "Ordinal",
      "value": "0"
    },
    {
      "name": "FunctionAddress",
      "value": "0x74503534"
    }
  ],
  "repeated": 0,
  "id": 100
}
```

but we have no idea what 0x77501fd7 corresponds to (0x7750) is only referenced in relation to these calls.

**Comment by yelhamer** [comment]
> if we want to correlate an API call with the source binary, this would be useful.

I think this wouldn't be useful in a lot of cases, such as if a binary is unpacking to a dynamically allocated memory region, or loading a second stage.

These addresses would be useful if one wants to inspect the memory dump. Perhaps we should keep this in mind for future use.
