### ISSUE TITLE
minidump: wrong(?) address to compute RVA

### ISSUE THREAD

**Issue by atxr** [mandiant/capa#1659]
*Regarding the MiniDump script pushed recently [here](https://github.com/mandiant/capa/blob/willi/mdmp/scripts/show-mdmp.py) by @williballenthin*

I don't really know if it's a feature or an error, but the address shown at the beginning of each line are reset to 0 at the beginning of each new object.

<img width="381" alt="image" src="https://github.com/mandiant/capa/assets/27704776/e2ede53b-5ac3-4cdc-a6a6-56104f36b877">

This isn't very handy to check an object at a given RVA in the file.
I was wondering if this was on purpose, and if so, I'll dig to add a feature to the script to show the current RVA.

**Comment by williballenthin** [comment]
this is the default behavior of vivisect vstruct and how it renders with the `tree` method. i'm not sure if this is intended or not, and if it's easy to patch.

**Comment by williballenthin** [comment]
line 300 is the relevant line in the script. it's just meant to be an exploration so feel free to change this however you'd like.

**Comment by williballenthin** [comment]
ah the bug is in `vivisect/vstruct/defs/minidump::Minidump.tree()`. it provides its own custom renderer that doesn't set the prefix as the file offset. 

you could provide a local implementation in our script or propose a fix upstream, if it bothers you.

**Comment by atxr** [comment]
Thanks for the tip, I think I'll fix it locally because it's not really a bug!
