### ISSUE TITLE
IDA Plugin Hangs on Plugin Launch

### ISSUE THREAD

**Issue by xorhex** [mandiant/capa#1661]
### Description

Throws an error upon first use (IDA Plugin) due to the rule path not being set.  Can't cancel out to set the rule path.  Have to force close IDA as nothing responds.

### Steps to Reproduce

1. Install plugin
   1. git clone https://github.com/mandiant/capa.git
   2. pip install -U capa/
   3. ln -s ~/capa/capa/ida/plugin/capa_explorer.py ~/.idapro/plugins/
2. Launch IDA64 (Linux version)
3. Edit -> Plugins -> Flare capa explorer
4. Error message pops up
![capa_error](https://github.com/mandiant/capa/assets/40742023/130efc1c-613f-4e0c-a184-e7f96e529cd5)
5. Close the popup to see this
![Screenshot from 2023-07-21 13-20-33](https://github.com/mandiant/capa/assets/40742023/2a7433a8-694c-4e24-a389-86986e4d698d)
6. Cancel does not work.  Have to pkill IDA to close it as nothing seems to respond.

**Expected behavior:**

Catch the error and show a popup saying to set the rule path and then use the UI to set the rule path.

**Actual behavior:**

Causes IDA to hang.

### Versions

OS: Linux
Python: 3.11
CAPA: Cloned the latest as of [today](https://github.com/mandiant/capa/commit/4eabee7329e3e57a56bf4bc4744ad244abe9f27b)
IDA: Version 8.3.230608

**Comment by williballenthin** [comment]
thanks for the thorough bug report @xorhex! we'll address this as soon as we can, which should be easy to reproduce with the details above.

**Comment by mike-hunhoff** [comment]
Thanks all for reporting and proposing temporary fixes. This bug is resolved in #1693.
