### ISSUE TITLE
Dynamic: Statement construction for mixed-scope rules

### ISSUE THREAD

**Issue by yelhamer** [mandiant/capa#1672]
This issue tracks the assumptions made in this PR: #1671 

#### 1. Allow rule authors to specify only one scope:
I think that we shouldn't enforce rule authors to specify both scopes for a rule, since some rules might only make sense in one analysis context/flavor (static or dynamic). An example of such case would be a rule for detecting xor-based de-obfuscation; no sandbox (to my knowledge) reports information on the instructions found within the binary, which makes this such rule exclusive to static capability extraction/analysis since there are no dynamic equivalents to it.

#### 2. Specifying just one flavor implies that the other one is invalid:
To extend on the previous point, I think that we should allow rule authors to flag that a rule is invalid for a certain analysis context. Two main ways of accomplishing this that come to mind; the first is to use a dedicated explicit keyword such as "invalid" or "none" to specify that the rule is not valid in that flavor, and the second is to assume that specifying only one flavor means that the other one is invalid. Of the two, I prefer the second since it's less explicit and should make rule writing easier. For example, if a rule author is trying to detect some instruction level capabilities at basic block, they shouldn't be concerned with the dynamic interpretation of their rule, and should just specify the static scope and get to working...

#### 3. No scopes keyword implies the `function` and `process` scopes:
To keep things ergonomic for rule authors, I suggest assuming that a missing scopes keyword implies a static scope of `function`, and a dynamic one of `process`. A similar assumption is present in the current static version of capa, wherein a missing `scope` keyword implies that the rule's scope is `function`. Therefore, I think it would only be logical to extend this assumption into the newer static/dynamic version of capa.

The function and process scopes were chosen since those are the most inclusive scopes (in terms of feature support), and because I believe that it's what a rule author would most likely have in mind when writing a rule. Using a `thread` scope seems fine to me as well.

One concern might be raised with regards to the previous point and this one, and it is that rule authors might assume that since specifying no scopes implies the function and process scopes, then specifying just the static scope for example implies the process dynamic scope; and I somewhat agree with this concern...

My reasoning is that if a rule author does not specify the scopes keyword then it's most likely because they're righting a common/generic rule (matching api's for example), however, if they specify just one scope, then that most likely implies that they are trying to express some logic in a specific building block (instruction, basic block, thread, etc.), and it's therefore safe to assume that the other scope is invalid unless the rule author explicitly specifies it. This is just speculations however 🤷... So I am curious to hear your thoughts...

#### 4. Don't prune rule statements according to the execution context:
Regarding the pruning of statement trees to have only the features that can be extracted in that analysis context (static or dynamic), I can see only two positives for doing that. The first one is to make things more sleek by not having redundant features that can never be matched anyways, and the second is to possibly make the code more performant (memory and time wise) by reducing the size of the rule set. However, I think that in actuality and in the grander scheme of things, these two points are less valid than they might seem.

Regarding the first positive, I believe that having a discrepancy between the features that each extractor supports is inevitable, since different sandboxes provide different output; for example, CAPE can be configured to skip the static analysis of the file and thereby not yield the file-exclusive features. Because of this, I feel like we can't fully escape having rule statements with redundant features that aren't going to get used. On the other hand, introducing pruning logic to the code is bound to make the code more complex and less-elegant, especially considering the fact that we'd need to update how rule set caching is done to prevent loading cached static rules in a dynamic context, as well as making sure no invalid features are present in rules, etc.. Consequently, I feel like the added elegance of having only context-specific features in the rule set would be offset by all the added code to do the pruning and handle the caching corner cases.

As for the second point, I believe having less features at each rule's level is not going to improve the code's space/time complexity considerably, since the number if redundant features in the rule set is not that significant. Furthermore, adding the extra logic that does the pruning should offset any performance advantages in my opinion.

#### 5. Filter the rule set according to the execution context:
Relating to the previous point, I think a more appropriate rule-filtering mechanism would be to remove non-usable rules from the rule set that gets passed to the extractor. This can be easily done — in terms of complexity and added code —, and would indeed make the code more performant. This would also not impact the rule caching.

#### 6. Normalizing the use of `Scopes` for the `build_statements()` function:
I think replacing all uses of the `Scopes` (singular) object with the `Scopes` (plural) one makes the code for the `build_statements()` function more clean and elegant. One downside is that it create several objects on the fly for the garbage collector to handle, but this can be circumvented keeping track of the created instances and not creating duplicate ones.

The strategy I'm proposing to avoid creating duplicate objects is to decorate the `__new__` dunder method with the `functools.lru_cache()` decorator, which ensures that if capa is trying to instantiate a `Scopes` object with the duplicate values (scopes), then the preexisting `Scopes` object would be returned instead.

**Comment by williballenthin** [comment]
I'm sitting here in vacation finding myself nodding along the whole way through this explanation! Thanks for taking the time to write things up in detail. I particularly appreciated how you considered both sides of some decisions. 

I'm in total agreement with everything, except (3) and maybe (6). 

(6) seems reasonable and may improve performance. But maybe also not. Either way, it seems like something that can be experimented on its own, not necessarily with the other upcoming changes. So I'd suggest that you try this out in its own branch. And, please, use benchmarks to demonstrate the changes are worthwhile (or not! that's a useful result too). 

(3) I agree more with the idea that having no scope implies no support, so if no scopes are specified at all, then the rule doesn't work anywhere. At least, I found this most consistent and easy to explain. Of course I'm open to further discussion and input from others. 

I think you can plan to move ahead with the ideas discussed in this issue. Nice work!

**Comment by yelhamer** [comment]
Thanks for taking the time-off to reply, it's much appreciated :D

Regarding the benchmarks, I somewhat agree too... I do think that it's premature-optimization to some extent. Just didn't like the idea of having like 500-ish equal `Scopes` objects in memory at the same time. I'll try to do some benchmarks and if that decorator doesn't make things worse then I think we should keep it, else we should get rid of it I think.

As for the 3rd point, I think your suggestion makes sense and it would make the code much simpler. The only downside I can think of (which is the upside to why I chose to keep the scopes assumptions) is that it makes things simpler for people who might be just test-writing rules, since it's one less meta field to configure. So I think I'll go with your suggestion on that.

Thanks again for the review and enjoy the rest of your vacation! :)

**Comment by yelhamer** [comment]
Closed in #1671
