### ISSUE TITLE
move matching logic into its own namespace

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1684]
within `main`, we have a lot of code for finding capabilities: https://github.com/mandiant/capa/blob/master/capa/main.py#L122-L339

more than 200 lines for static analysis, and soon we'll have parallel implementations for dynamic analysis. this seems like too much code for the `main` script, which should probably be focused on handling CLI args and rendering the results.

we should move this logic into their own namespaces. this will be a breaking change for users that invoke capa as a library; however, its a good change for the long term health of capa.

**Comment by yelhamer** [comment]
> this will be a breaking change for users that invoke capa as a library

Perhaps we could still provide an `extract_capabilities()` function in main that calls into the new namespace, for backwards-compatibility reasons.

**Comment by williballenthin** [comment]
good idea. we can survey the scripts in `capa/scripts/*` to see how they reach into `capa.main` and try to preserve some level of compatibility.

**Comment by mr-tz** [comment]
addressed as part of #1948?

**Comment by williballenthin** [comment]
closed in #1948
