### ISSUE TITLE
cannot install capa locally in "editable" mode

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1694]
This appears to be a result of switching to `pyproject.toml` file:
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Exclusions\capa
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

Not sure if "editable" mode is possible now or if a different command is needed. Depending on the outcome we need to update our documentation: https://github.com/mandiant/capa/blob/master/doc/installation.md#2-install-the-local-source-code

**Comment by williballenthin** [comment]
we do an editable install in CI here: https://github.com/mandiant/capa/blob/5400576d4e29c7f2787bfe805af6951dfdbef817/.github/workflows/tests.yml#L38

can you provide more details about the setup you're seeing this error in?

**Comment by mike-hunhoff** [comment]
Looks like my problem was an outdated `pip`. I was using `﻿﻿21.2.3` with Python 3.10 on Windows. Upgrading to `23.2.1` resulted in the expected behavior. Thanks for investigating @williballenthin !
