### ISSUE TITLE
installing capa locally via "python -m pip install ." does not install capa packages e.g. capa.ida, capa.render, etc.

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1695]
This may be a result of switching to `pyproject.toml` file? The lack of packages prevents capa explorer from being installed and executed locally.

Output:
![Screen Shot 2023-08-08 at 11 00 32 AM](https://github.com/mandiant/capa/assets/42192796/cd4162c3-dce4-4388-ad38-4a5a6c8524c6)

Expected:
![Screen Shot 2023-08-08 at 11 03 42 AM](https://github.com/mandiant/capa/assets/42192796/bcee46c7-d876-4abd-9f9e-da2d886d063c)

Oddly enough `python -m pip install flare-capa` appears to work as expected.

**Comment by mike-hunhoff** [comment]
If the commands we used need to change then we need to update our documentation.

**Comment by williballenthin** [comment]
we use `pip install -e .` in CI and that's been working fine. i don't know if/how using *not* -e works. thoughts?

**Comment by williballenthin** [comment]
if users want to install from local source in non-editable mode, we should instruct them to do a build of the whl (`python -m build`) and then install that.

**Comment by williballenthin** [comment]
@mike-hunhoff what versions of pip, python, etc. are you using?

here is capa is installing in non-editable mode on linux:

![image](https://github.com/mandiant/capa/assets/156560/b4f5a789-b2b3-4dad-8707-25bea991c898)

**Comment by mike-hunhoff** [comment]
Looks like my problem was an outdated `pip`. I was using `﻿﻿21.2.3` with Python 3.10 on Windows. Upgrading to `23.2.1` resulted in the expected behavior. Thanks for investigating @williballenthin !
