### ISSUE TITLE
extractors loaded for unrelated tests

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1707]
in fixtures.py at the top level, we call `get_*_extractor` for a selection of samples to compute their hashes. because this is at the top level, this is done at import time, rather then when the relevant test is invoked. this slows down the invocation of other tests.

https://github.com/mandiant/capa/blob/19495f69d747bff25ae3bfe4022a6a7c88d18a68/tests/fixtures.py#L668-L670

**Comment by williballenthin** [comment]
since these fixtures aren't used by more than one test, they can be just as easily embedded in the single test file

**Comment by yelhamer** [comment]
fixed in #1708
