### ISSUE TITLE
fix vverbose rendering of scopes

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1710]
![image](https://github.com/mandiant/capa/assets/156560/ad8848bc-73f9-4624-aa2a-d97006aebd37)

**Comment by williballenthin** [comment]
this is because when we render a rule in vverbose mode, we start by rendering the scope at which the matching begins, like "instruction @ 0x401000"

however, now that a rule may have multiple scopes associated with it, we don't know which one is relevant. we can inspect `result_document.meta.flavor` now to find out.

**Comment by yelhamer** [comment]
closed in #1713
