### ISSUE TITLE
AttributeError: module 'idaapi' has no attribute 'get_input_file_md5'

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1730]
https://github.com/mandiant/capa/blob/bb2b1824a9639ab47a5f61d6ff08d1fb38d5c173/capa/features/extractors/ida/extractor.py#L38C36-L38C36

**Comment by williballenthin** [comment]
should use `ida_nalt.retrieve_input_file_md5`

https://www.hex-rays.com/products/ida/support/idapython_docs/ida_nalt.html#ida_nalt.retrieve_input_file_md5

**Comment by mr-tz** [comment]
retrieve_input_file_md5
and also retrieve_input_file_sha256  or better:

get_file_md5 and get_file_sha256 from capa/ida/helpers.py

**Comment by mr-tz** [comment]
Should we prefer to use the helper routines to handle API versions which return bytes vs. strings?
