### ISSUE TITLE
add scope terms to specify unsupported

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1744]
with the introduction of multiple flavors of analysis (static, dynamic), rules should specify the scope for each flavor, such as `static: function, dynamic: thread`.

we should add a new scope term to specify that a rule cannot be used in a given flavor, such as a rule that relies on instruction mnemonics cannot be used in the dynamic analysis flavor. it might look like this: `dynamic: unsupported`.

today, a *missing* scope specifier has this effect; however, we should require a scope specifier for all flavors of all rules. this avoids the potential for rule authors to introduce a new rule with accidentally missing scope, which we then cannot easily tell if this was intended.

we should also consider (temporarily) supporting the scope term `unspecified` to indicate that the rule scope has not yet been determined, such as by our large scale migration of static-only rules to static+dynamic rules. once all rules have been migrated, then we should remove support for this scope term.

**Comment by yelhamer** [comment]
closed in #1748 
associated rules: https://github.com/mandiant/capa-rules/pull/816
