### ISSUE TITLE
Potentially wrong method name used in Binja backend

### ISSUE THREAD

**Issue by aaronatp** [mandiant/capa#1754]
In capa/features/extractors/binja/function.py, the extract_function_calls_to() function is defined as:

    
    def extract_function_calls_to(fh: FunctionHandle):
        """extract callers to a function"""
        func: Function = fh.inner
    
        for caller in func.caller_sites:
            # Everything that is a code reference to the current function is considered a caller, which actually includes
            # many other references that are NOT a caller. For example, an instruction `push function_start` will also be
            # considered a caller to the function
            if caller.llil is not None and caller.llil.operation in [
                LowLevelILOperation.LLIL_CALL,
                LowLevelILOperation.LLIL_CALL_STACK_ADJUST,
                LowLevelILOperation.LLIL_JUMP,
                LowLevelILOperation.LLIL_TAILCALL,
            ]:
                yield Characteristic("calls to"), AbsoluteVirtualAddress(caller.address)

I was looking at the Binja documentation and it looks like "call_sites" is a method name for a Binja Function object but "caller_sites" is not (https://api.binary.ninja/binaryninja.function.Function.html). Should "for caller in func.caller_sites" be changed to "for caller in func.call_sites"?

**Comment by mr-tz** [comment]
cc: @xusheng6

**Comment by xusheng6** [comment]
There seems to be some issues with our documentation generation. The `caller_sites` is present here: https://dev-api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.caller_sites. Though it is missing from this page: https://api.binary.ninja/binaryninja.function.Function.html. 

I have created this issue in our issue tracker to track it: https://github.com/Vector35/binaryninja-api/issues/4653. I think this issue can be closed

**Comment by xusheng6** [comment]
@aaronatp `caller_sites` and `call_sites` are two different properties. The `caller_sites` are places where the code call this function, `call_sites` are places inside the current function where it makes a call to other code. The code should use `caller_sites`

**Comment by williballenthin** [comment]
thanks for the explanation @xusheng6!
