### ISSUE TITLE
investigate feasibility of a BinExport2 backend

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1755]
BinExport is an intermediate representation of disassembly produced by various tools, like IDA, Binary Ninja, Ghidra, etc. The data is stored in a ProtoBuf format: https://github.com/google/binexport/blob/main/binexport2.proto

It includes many of the things that capa needs:
  - instructions
  - operands
  - functions, basic blocks
  - strings

Some other things are missing:
  - section names
  - data references

Investigate the feasibility of building a backend that relies upon BinExport. Consider the tradeoffs of requiring the original file (such as for missing metadata, like sections, or data references) versus self-contained protobuf.

**Comment by williballenthin** [comment]
- instruction features
    - api ✓
    - number ✓
    - string and substring ✓
    - bytes ✗ (but possible alongside PE/ELF)
    - offset ✓
    - mnemonic ✓
    - operand ✓
    - namespace ?
    - class ?
    - property ?
  - function features
    - function-name ✓
  - file features
    - string and substring ✗ (but possible alongside PE/ELF)
    - export ✗ (but possible alongside PE/ELF)
    - import ✗ (but possible alongside PE/ELF)
    - section ✗ (but possible alongside PE/ELF)
    - namespace ✓
    - class ✓
  - global features
    - os ✗ (but possible alongside PE/ELF)
    - arch ✓
- characteristic
    - embedded pe ✗ (but possible alongside PE/ELF)
    - forwarded export ✗ (but possible alongside PE/ELF)
    - mixed mode ✗
    - loop ✓
    - recursive call ✓
    - calls from ✓
    - calls to ✓
    - tight loop ✓
    - stack string ✓
    - nzxor ✓
    - peb access ✓
    - fs access ✓
    - gs access ✓
    - cross section flow ✓
    - indirect call ✓
    - call $+5 ✓
    - unmanaged call ✗

**Comment by r0ny123** [comment]
Since the topic came up, maybe we consider this one https://github.com/quarkslab/quokka too?

**Comment by williballenthin** [comment]
Do you use Quokka or know of people that do? Seems very reasonable if so, though we don't want to maintain unused code.

**Comment by r0ny123** [comment]
Unfortunately, no. You're right that it's still in the early stages and not widely used at this moment.
