### ISSUE TITLE
ghidra: find_byte_sequence incorrectly bounded

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1756]
The following code incorrectly bounds Ghidra's `findBytes` to `1` as the intent of the function is to return all matches:

https://github.com/mandiant/capa/blob/19b8000c004984045628d62826436fb471e54cfa/capa/features/extractors/ghidra/helpers.py#L39

Unfortunately, `findBytes` must have an upper bound set, we can't simply tell it to find all matches (AFAIK). The examples I have seen use Java's `Integer.MAX_VALUE` as the upper bound which probably works fine for our use cases.

We should be able to access Java's `Integer.MAX_VALUE` with something like:

```python
import java.lang

print(java.lang.Integer.MAX_VALUE)
```

**Comment by colton-gabertan** [comment]
Thanks for catching this, I've tested in the interpreter and it pulls a lot more results. 

From mimikatz.exe_:
<img width="403" alt="image" src="https://github.com/mandiant/capa/assets/66766340/ee376013-f4a3-44f4-a16d-30b101d4f884">
