### ISSUE TITLE
dotnet: emit enclosing class information for nested classes

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#1780]
capa does not emit the `<namespace>.<class>` of the class that encloses a nested class.

e.g when processing [`Settings.System::PutInt`](https://learn.microsoft.com/en-us/dotnet/api/android.provider.settings.system.putint?view=xamarin-android-sdk-13#android-provider-settings-system-putint(android-content-contentresolver-system-string-system-int32)), capa emits only `System::PutInt` when ideally capa would emit something like `Android.Provider.Settings.System::PutInt`.

The suggestion of using `Android.Provider.Settings.System::PutInt` could be confusing though because, based on how capa currently treats namespaces + classes, this makes it appear that `Android.Provider.Settings` is a namespace when it is a class. Alternately, capa could take the same route as `dnSpy` by emitting `Android.Provider.Settings/System::PutInt` where `/` denotes a nested class signifying that  `Android.Provider.Settings` is the enclosing class and `System` is the nested class.

How should capa emit features for `Android.Provider.Settings/System::PutInt`?

capa currently emits:
- `namespace(Android.Provider)`
- `class(Android.Provider.Settings)`
- `class(System)`
- `import(System::PutInt)`
- `api(System::PutInt)`

I propose that capa emit:
- `namespace(Android.Provider)`
- `class(Android.Provider.Settings)`
- `class(Android.Provider.Settings/System)`
- `import(Android.Provider.Settings/System::PutInt)`
- `api(Android.Provider.Settings/System::PutInt)`

Reading the ECMA specs, I can't find anything that states a max nesting depth for .NET types. Therefore, we should not assume a max depth when coding this new feature.

capa should handle nested classes for both locally defined (`TypeDef`) classes and imported (`TypeRef`) classes. For `TypeDef` classes, capa should be able to use the `NestedClasses` (0x29) table. For `TypeRef` classes, capa should be able to use the `ResolutionScope` index where a `TypeRef` is nested if its `ResolutionScope` index is a `TypeRef` index.

**Comment by bkojusner** [comment]
Working on it!
