### ISSUE TITLE
split up the required dependencies by backend

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1810]
right now, we install all dependencies for all (library) users: https://github.com/mandiant/capa/blob/40d9587fa4a49cc120c39920aed71d2e821ac203/pyproject.toml#L35-L52

however, some users might not be using IDA while others might not use Ghidra/dnfile/BN/etc.

we should categorize the dependencies by backend and install only what is needed. for example `pip install capa[ida,dncil]`. core capa should require as few dependencies as possible.

**Comment by williballenthin** [comment]
currently importing `capa.main` requires viv due to reference in `elf.py`

**Comment by mr-tz** [comment]
We should then also test all install configurations... 😟

**Comment by williballenthin** [comment]
I think we should at least test "with everything" and "with nothing".

**Comment by williballenthin** [comment]
i'm not sure if its possible to provide a default collection, like:

    pip install flare-capa

but if the user provides something more specific, use that instead, like:

    pip install flare-capa[ui,utils,vivisect-backend]


otherwise, its a breaking change, and we'll have to encourage users to use `pip install flare-capa[all]` unless they have special needs.

**Comment by mr-tz** [comment]
so we should keep this as simple as possible, e.g.:
- core
- ui
- optional

then we could have checks in the code that have fallbacks if an UI/optional module is not available

**Comment by williballenthin** [comment]
I think it's been a good exercise to review the dependencies and update documentation (esp. with pyproject.toml). Given that there are no external requests to split up the dependencies into collections, I don't think we should pursue that at this time. It seems possible to do, but it's a substantial breaking change, and there's not an immediate tangible benefit.

I plan to open a PR shortly with some tweaks to importing (deferring some imports to closer to their usage) and documenting the dependencies with pyproject.toml. Then I'll propose that we close out this issue.

**Comment by mr-tz** [comment]
sounds good!
