### ISSUE TITLE
find a replacement for halo

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1812]
we use the halo package to show a spinner during long running computations. unfortunately, the package hasn't been updated in a long time, and while this typically isn't an issue itself, it calls a deprecated API:

```
.../capa/.direnv/python-3.11/lib/python3.11/site-packages/halo/halo.py:497: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
    self._spinner_thread.setDaemon(True)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by williballenthin** [comment]
maybe https://pypi.org/project/yaspin/ ?

**Comment by bpshaver** [comment]
Was cruising for issues with `good-first-issue` and saw this. Took a crack at it, but I still need to make sure it streams to stderr:

https://github.com/bpshaver/capa/commit/ac742f7ec8ca663cbdb08a22bb4dbb404793101b

**Comment by bpshaver** [comment]
It looks like `yaspin` only writes to `std.out`

**Comment by williballenthin** [comment]
the STDOUT consideration is around things like: `capa.exe > output.txt` but still wanting to see the progress bar while it executes?

**Comment by bpshaver** [comment]
Yeah, I read that issue too. At first I was thinking of just disabling the spinner if stdout is not a TTY, but now I see that you want the spinner on stderr while stdout safely goes through the pipe. 

Would it be too hacky to just patch `sys.stdout` to `sys.stderr`? I'll give it a shot.

**Comment by bpshaver** [comment]
```python
import sys
from unittest.mock import patch

with patch("sys.stdout", sys.stderr):
    with yaspin(text="spinning"):
```

Something like this accomplishes the job if you're not writing to stdout within the context of the spinner. In the second instance of `main.py`, though, there are calls to the `logger` methods, and I'm unsure how they are affected by the patch. Probably best to modify the handler for the logger so its explicit about going to stdout or stderr.

I've updated my branch with this patch applied to `main.py`
