### ISSUE TITLE
collect file extensions seen in CAPE sample imports

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1823]
https://github.com/mandiant/capa/blob/b8b55f4e19a0da8d08266c67e4bcc1b82f17245e/capa/features/extractors/helpers.py#L57-L59

**Comment by williballenthin** [comment]
```console
❯ jq ".static.pe.imports[].dll" mnt/public_full_reports/00* | tr "[:upper:]" "[:lower:]" | sed -e "s/^.*\(\.[^.]*\)\"/\1/g" | sort | uniq -c | sort -nr
   1313 .dll
     28 .drv
      1 .ocx

```

**Comment by mr-tz** [comment]
I propose to remove this in an upcoming PR to address #1815.

**Comment by mr-tz** [comment]
Although, should we keep the DLL name for imports? We'll always have these.

**Comment by mr-tz** [comment]
Are we fine leaving it with .dll and .drv?

**Comment by williballenthin** [comment]
![image](https://github.com/mandiant/capa/assets/156560/9e33c98e-6f52-4d7c-a08d-d666052611a5)

**Comment by williballenthin** [comment]
![image](https://github.com/mandiant/capa/assets/156560/dbdb8510-c872-4954-ad99-53ac650b39ca)

**Comment by mr-tz** [comment]
can this be closed?
