### ISSUE TITLE
add pip-audit to CI

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1857]
i would suggest you  to add pip-audit git action workflow, we have it for pip as we export poetry one https://github.com/kevoreilly/CAPEv2/blob/master/.github/workflows/pip-audit.yml, you can use `pip-audit .` to audit pyproject.toml

_Originally posted by @doomedraven in https://github.com/mandiant/capa/issues/1856#issuecomment-1814122931_

**Comment by doomedraven** [comment]
this should works https://github.com/mandiant/capa/pull/1858

**Comment by mr-tz** [comment]
closed via #1858, thanks @doomedraven!

**Comment by doomedraven** [comment]
That was fast 😍
