### ISSUE TITLE
Load .json.gz files directly

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1883]
Should we add support to load compressed JSON reports directly?

This simplifies loading files. Tests support this currently but not capa main.

**Comment by williballenthin** [comment]
we should be able to taste the start of a compressed file and guess if it's a JSON report without too much effort. 

the logic of doing the file type detection is getting a little complex, but there seems to be good reason for it all. 

i think we should consider it.

**Comment by Exterminator11** [comment]
hey @williballenthin and @mr-tz, I would love to work on this issue. If you could give me a starting point it would be great😃.
Thanks

**Comment by mr-tz** [comment]
Here's how tests load json.gz files: https://github.com/mandiant/capa/blob/7584e4a5e6205029960465f64216ed72cd53c53c/tests/fixtures.py#L193

The main capa code should handle this somewhere around the usage/implementation of this function: https://github.com/mandiant/capa/blob/7584e4a5e6205029960465f64216ed72cd53c53c/capa/helpers.py#L87
