### ISSUE TITLE
Create v7.0-beta release

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1884]
These issues should be double-checked/addressed before:

- [x] #1880
- [x] #1882

Would then be great to get interested analysts testing this before the official release.

**Comment by mr-tz** [comment]
To add to release notes:

- The divergence of several classes into static and dynamic equivalents: with this new release, many classes and concepts have been split up into static ones which are mostly identical to the original ones, and newly-added dynamic ones. For example, the legacy FeatureExtractor class has now been renamed to StaticFeatureExtracor, which contrasts its sister class: DynamicFeatureExtractor. Old and future contributors should take this change into account, since now all static feature extractors must be implementations of the same class.

- The addition of a new capabilities capa module: starting from version 7.0, we have moved the component responsible for feature extractor from main.py to a new module named: capabilities. Now, users wishing to utilize capa’s feature extraction abilities should use that module instead of importing the relevant logic from the main file.

- Use of Pydantic models for the sandbox-based feature extractors: for the sandbox-based feature extractors, we are using Pydantic as a means of maintaining these reports. Contribution of other Pydantic models for other sandboxes is very welcomed!

**Comment by as0ni** [comment]
Hi there @mr-tz. Just curious when you thought capa 7 beta might be ready for use with the latest capa-rules collection. 

Thanks for all your efforts to create and maintain this amazing tool!

**Comment by mr-tz** [comment]
Happy New Year! We plan to get this done in January - starting off 2024 with a banger ;)

**Comment by mr-tz** [comment]
Outstanding tasks are complete and we can create the beta release now!

**Comment by mr-tz** [comment]
See https://github.com/mandiant/capa/releases/tag/v7.0.0-beta and https://github.com/mandiant/capa-rules/releases/tag/v7.0.0-beta
