### ISSUE TITLE
loading rules error in capa explorer plugin in ida pro 

### ISSUE THREAD

**Issue by mounirthabet** [mandiant/capa#1903]
i have a problem loading rules in Cap Explorer only Capa rules version 4.0.0 can be loaded  the new version 6.0.0 Gives me many errors

**Comment by mike-hunhoff** [comment]
Thank you for reaching out @mounirthabet . The version of capa that you are using must match the version of the capa rules that you are using. You will need to upgrade capa to the latest version to use the latest version of the capa rules.

Check out our [capa explorer installation instructions](https://github.com/mandiant/capa/tree/master/capa/ida/plugin#installation) for more information.

Let us know here if upgrading to the latest version of capa solves your issue.

**Comment by mr-tz** [comment]
Hey @mounirthabet, did Mike's comment help?

**Comment by JCoonradt** [comment]
Would it be helpful to add an automatic check to see if the version of Capa installed matches the version of Capa rules installed? This way, if the versions don't match, the user will be given an appropriate error statement explaining the issue so they can know the problem and how to resolve it. I can implement this if you think it would be a good idea!

**Comment by williballenthin** [comment]
@JCoonradt unfortunately the rules don't have an embedded version so it's not easy to tell if there's a mismatch

**Comment by mr-tz** [comment]
For reference, the settings dialog in capa explorer shows a link to download the correct rules.

Please reopen here if this issue persists.
