### ISSUE TITLE
pip install fails on python3.12 due to pyyaml+Cython3 issue

### ISSUE THREAD

**Issue by FelixBer** [mandiant/capa#1919]
pip3 install flare-capa on windows 10 with python 3.12 fails with

```
        File "C:\Users\usar\AppData\Local\Temp\pip-build-env-kt6p__qc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
```
which seems to be this issue with cython3+pyyaml https://github.com/yaml/pyyaml/issues/601
As far as I can see capa 6.1.0 requires pyyaml 6.0.1 which should mitigate the problem.
But for some reason the install command tries to install both capa 6.0 and 6.1...?

```
Collecting flare-capa
  Downloading flare_capa-6.1.0-py3-none-any.whl.metadata (27 kB)
Collecting pyyaml==6.0.1 (from flare-capa)
  Downloading PyYAML-6.0.1-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
....
Collecting flare-capa
  Downloading flare_capa-6.0.0-py3-none-any.whl.metadata (28 kB)
Collecting pyyaml==6.0 (from flare-capa)
  Downloading PyYAML-6.0.tar.gz (124 kB)
```

Do you know why? What's the official way to work around this?

Attaching the full install log
[capa_error.txt](https://github.com/mandiant/capa/files/13854749/capa_error.txt)

**Comment by mr-tz** [comment]
capa does not work on Py3.12 yet, see https://github.com/mandiant/capa/issues/1854

**Comment by FelixBer** [comment]
ok, thanks.
