### ISSUE TITLE
update copyright to 2024

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1926]
update here: https://github.com/mandiant/capa/blob/9e5cc07a48fada9042e106c0b21504c80d58af21/.github/flake8.ini#L41

then fix the linter violations, and/or use a recursive sed

**Comment by JCoonradt** [comment]
At the bottom of the LICENSE.txt file on line 190, it still says Copyright (C) 2023 Mandiant, Inc. Should I update this?

**Comment by williballenthin** [comment]
every copyright instance of 2023 should be replaced with 2024 across all files

**Comment by JCoonradt** [comment]
Great! I fixed it! Also, I was wondering if I had a way to improve the Capa program (an enhancement more than an issue, but it does resolve #1903), would I simply commit it and explain what my change is and why it is beneficial? I will install IDA pro to test it as well. Or is there another process I should use when making enhancements? Sorry to bother you with this, I am just new to open source and really excited to get involved with this project!

**Comment by mr-tz** [comment]
I think we don't need to do this, see https://nexb.com/do-you-really-need-to-update-the-copyright-each-new-year/:

> Popular open source projects like [Google’s Go](https://github.com/golang/go/blob/master/LICENSE), [Microsoft’s VS Code](https://github.com/microsoft/vscode/blob/main/LICENSE.txt), and [Netflix’s Hystrix](https://github.com/Netflix/Hystrix/blob/master/README.md#license) already just list the first year of the copyright. Others dropped years altogether – Facebook [removed years](https://github.com/facebook/react/commit/b87aabdfe1b7461e7331abb3601d9e6bb27544bc) from React, and so did GitHub, Facebook and Amazon.

**Comment by williballenthin** [comment]
let's also check with Google's open source office to see what they recommend. i don't feel strongly in any direction.

**Comment by williballenthin** [comment]
Google policy is to list the year that the file was introduced. We should not be updating the date from year to year. 

We can use git history to figure out when each file was first added. It won't fully recover when files are moved around, but it's better than what we do today. 

It's unfortunate that the header can't be consistent throughout and therefore easy to lint and check. Oh well. 

I'm sympathetic to the positions taken by the other big projects, though I think we should follow the guidance of our org here. Thoughts?

**Comment by mr-tz** [comment]
I think using that policy makes sense. The initial update will be slightly more work, but then moving forward it should be easy.

**Comment by williballenthin** [comment]
Sounds perfect. 

Of course, I'd discourage you from doing this manually. Perhaps a one-off Bash or Python script can do it more quickly.

**Comment by mr-tz** [comment]
Yes, probably. The regex and some files probably need updating though.

**Comment by Atlas-64** [comment]
If @JCoonradt isn't working actively on this issue anymore, is it okay if I give it a try? @williballenthin @mr-tz

**Comment by mr-tz** [comment]
Yes, I think you can go ahead.

**Comment by Atlas-64** [comment]
Sorry for the delay; looking at the code right now, and if I understand right, any instance of copyright across any file type should be  changed with its file origin year; asking cuz currently writing a recursive sed so I thought I should clear my doubt if I should just run it through all python executables (and also look for any regex statements) only or should I run it all across the repo  looking for any instance of copyright and do the above action @mr-tz

**Comment by williballenthin** [comment]
@Atlas-64 yes, it should be across all source files. Please review the resulting diff and use your judgement to ensure only the relevant changes are made. The purpose here is to set only the copyright headers so that people that read the code understand the copyright and origins.

**Comment by Atlas-64** [comment]
Okay, cool. I am done running the script; I just had a question about the license. Do I update it to 2024 or keep it as 2020(its origin) and the same doubt for the regex (just change it to 2024?) . 
It works perfectly fine for everything else. I ended up just writing a powershell script and running through the whole repo, used gits commit history to get the origin, and changed it accordingly through a recursive, so we are good on that part. 
I just had a doubt about the above 2 will make a PR after changing them .Thanks for any help :) @williballenthin

**Comment by mr-tz** [comment]
We want to list the year that the file was introduced.

**Comment by mr-tz** [comment]
closed via #2027
