### ISSUE TITLE
Add citations file

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1929]
to make research papers easier, etc.

**Comment by JCoonradt** [comment]
I can do this! Would I just need to add a CITATION.cff file to the repository?

**Comment by mr-tz** [comment]
Yes, I'd follow this documentation https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by williballenthin** [comment]
i'm not quite sure what information we need to provide or the format it goes in. would you find a few other examples on Github and we can follow their template? I'd definitely appreciate your help here.

**Comment by JCoonradt** [comment]
Great, thank you that is very helpful! Who should I put down as the authors, as this is an open-source program? Also, do we have those authors' Orcid IDs? I think the Orcid ID part is optional, so I just need the authors' names.

**Comment by mr-tz** [comment]
I suggest:

- name: "The FLARE Team"

Or we could list the core team by name?

Reference: https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsreferenceauthors

**Comment by JCoonradt** [comment]
Thanks for the help! I will add the citation file under the name "The Flare Team" tonight!

**Comment by Atlas-64** [comment]
hi has a CITATION.cff been added by @JCoonradt , otherwise i would love working on this right away ,please do let me know

**Comment by Atlas-64** [comment]
@mr-tz where can 
I find the the relevant info for the core team or would just "The FLARE Team" suffice for the citation

**Comment by Atlas-64** [comment]
@mr-tz @williballenthin have made a PR update with a CITATION.cff please review and comment on any changes if possible.

**Comment by mr-tz** [comment]
closed via #2018
