### ISSUE TITLE
rename args.sample to args.input

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1946]
since the input file is not longer guaranteed to be an executable file to analyze (cape, freeze, result document), then we should rename the CLI argument from `sample` to `input` (?). we should do this in v7 since its a breaking change that goes along with the cape work.

**Comment by williballenthin** [comment]
thoughts @mr-tz @mike-hunhoff ?

**Comment by mike-hunhoff** [comment]
I agree a name change is due. I also like `file` as `input` makes me think of Python's `input` and that I could pipe/type/etc. data to capa.

**Comment by williballenthin** [comment]
> I also like file as input makes me think of Python's input and that I could pipe/type/etc. data to capa.

Good point, how about `input_file`?

**Comment by mike-hunhoff** [comment]
sounds good
