### ISSUE TITLE
Remove support for Python 3.8

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1966]
>  After that, it is expected that security updates (source only) will be released until 5 years after the release of 3.8 final, so until approximately October 2024. - https://peps.python.org/pep-0569/

```[tasklist]
### Tasks
- [ ] #1896
- [ ] #1912
- [x] update pyproject.toml to specify python 3.9
- [x] use dict[...] instead of Typing.Dict[...], etc.
```

**Comment by doomedraven** [comment]
i would suggest to go directly with 3.10 instead of 3.9, like for example ubuntu 20 comes with 3.8, but ubuntu 22 comes with 3.10, so there is 3.9 only in non LTS versions. just my 2 cents

**Comment by mr-tz** [comment]
this is coming soon, should we go with 3.9 or 3.10?

**Comment by doomedraven** [comment]
3.10 😜

**Comment by williballenthin** [comment]
To define the issue, "declaring support" (or "removing support for") means that:

  1. we update pyproject.toml specifying the minimum supported Python version, which prevents installation on lesser versions, and
  2. enables us to use language features from that version and earlier.

By keeping more versions of Python available, theoretically there are more users/environments that can install capa. But, in practice, who are these people? Especially in the age of docker containers and virtual environments.

Python 3.9 is supported (security patches) for the next year, until Oct 2025. https://devguide.python.org/versions/

So, the Python organization provides support for this audience.

According to pypistats.org, around 2% of capa downloads are for Python 3.9
https://pypistats.org/packages/flare-capa

![image](https://github.com/user-attachments/assets/37e9c267-5c5b-40dc-b7f5-039dd353e9d0)

Here are the upcoming language features of Python that we can start using:

https://web.archive.org/web/20240915170814/https://www.nicholashairs.com/posts/major-changes-between-python-versions/

![image](https://github.com/user-attachments/assets/616fb56a-b210-4978-8d7b-aa7549ee3a33)

![image](https://github.com/user-attachments/assets/06cf757a-ff30-4722-a7ff-ca14aba73844)

![image](https://github.com/user-attachments/assets/bb6b4542-55a5-4a96-a312-dca655ffbde7)

**Comment by williballenthin** [comment]
We could try dropping support for 3.9 but not use any new language features, and if noone complains after X amount of time (advertised in the readme/changelog/warning messages) then we could make it official (or revert and re-add support for 3.9).

**Comment by williballenthin** [comment]
Personally, I like the consistency of following Python.org, because then we don't have to make decisions ourselves and debate which language features are worth what user base.

OTOH, I think capa would use the following 3.10 language features reasonably heavily:

  - structural pattern matching
  - unions with pipe
  - type alias

**Comment by mr-tz** [comment]
Nice stats, thank you! I agree that 3.10 offers some cool new language features. For the <2% of Python 3.9 downloads I think the pros outweigh the few users (who can probably easily upgrade to a newer Python anyway).

**Comment by williballenthin** [comment]
if we do a point release soon (which I think we were planning to do), then lets include a note about this (and maybe warning when run under Python 3.8 or 3.9). then as soon as that's released, bump the minimum python version to 3.10 and start using those language features.

thoughts?

**Comment by mr-tz** [comment]
Sounds good to me!

**Comment by mr-tz** [comment]
Notably, Windows 7 will not be supported anymore as the last supporte Python is 3.8 (https://www.python.org/downloads/windows/).
