### ISSUE TITLE
ghidra: update CI Workflow to reflect recent Ghidrathon changes

### ISSUE THREAD

**Issue by colton-gabertan** [mandiant/capa#1976]
### Summary

The latest [release candidate](https://github.com/mandiant/Ghidrathon/releases/tag/v4.0.0-rc1) for Ghidrathon now includes an [installation script](https://github.com/mandiant/Ghidrathon/blob/main/util/ghidrathon_configure.py). This now outdates the method used in the Ghidra backend's [CI workflow](https://github.com/mandiant/capa/blob/fde1de3250ccb7c46d0ef36f60f830d679ea79c1/.github/workflows/tests.yml#L178-L192). Please update the workflow to use the new installer.

**Comment by mike-hunhoff** [comment]
Thank you for opening, great idea! With the latest changes to Ghidrathon we can download the pre-built extension and remove the Gradle build steps from our CI workflow.

**Comment by psahithireddy** [comment]
Hello, can I please take this up?

**Comment by mike-hunhoff** [comment]
Thank you for reaching out @psahithireddy - I've assigned this issue to you. The goal here is to update [capa's existing Ghidra test workflow](https://github.com/mandiant/capa/blob/c6b43d74927b8374e5970508d530e806acddd576/.github/workflows/tests.yml#L147-L203) to leverage the [simplified Ghidrathon v4 installation steps outlined in its README](https://github.com/mandiant/ghidrathon?tab=readme-ov-file#installing-ghidrathon). Specifically, we want to substitute building Ghidrathon with [downloading the latest pre-built release from GitHub](https://github.com/mandiant/Ghidrathon/releases/tag/v4.0.0).

As you already mentioned, let's also update the versions:

- Ghidra -> 11.0.1
- Ghidrathon -> 4.0.0
- Jep -> 4.2.0 (this is installed as part of the simplified Ghidrathon v4 steps)

Reach out here if you have any questions! 🚀

**Comment by psahithireddy** [comment]
Hi @mike-hunhoff, I have few questions
1. In the installation steps for ghidrathon, I believe you missed mentioning ` cd /util` to run requirements.txt and ghidrathon_configure.py.
2. Also, do I need to add the installation of requirements.txt into CI workflow as it only contains jep, which is already in CI workflow. 
Thanks :)

**Comment by mike-hunhoff** [comment]
The [Ghidrathon-v4.0.0.zip file](https://github.com/mandiant/Ghidrathon/releases/tag/v4.0.0) contains three files:
![Screenshot 2024-02-23 1 53 01 PM](https://github.com/mandiant/capa/assets/42192796/43fd2d23-1f85-4f97-93bb-7857a4d19c86)

`requirements.txt` and `ghidrathon_configure.py` can be used as described Ghidrathon's installation steps. The embedded `Ghidrathon-v4.0.0.zip` should be extracted directly to `<absolute_path_to_ghidra_install_dir>\Ghidra\Extensions`. From there, we can run the CI tests.

**Comment by psahithireddy** [comment]
Understood. My apologies for the bad PRs, I now found a way to trigger it without PR, in my local. Should I update the CHANGELOG too? 

Thanks a lot for your help!

**Comment by mike-hunhoff** [comment]
closed by #2020
