### ISSUE TITLE
add pager to page capa's long text output

### ISSUE THREAD

**Issue by s-ff** [mandiant/capa#2021]
### Summary

Implement a pager feature to handle extensive text outputs, allowing users to navigate capa's results and search efficiently.

### Motivation

Capa's output can sometimes be overwhelming, making it challenging to navigate and search (`/`) for specific rule matches. Adding a pager, like `less -R`, would provide an improved user experience. This setting should be optional, with the user being free to setup a pager tool; for example via `--pager <tool>` (or `$PAGER`).

### Describe alternatives you've considered

- [`click.echo_via_pager()`](https://click.palletsprojects.com/en/8.1.x/utils/#pager-support)
- [`pydoc.pager()`](https://docs.python.org/3/library/pydoc.html)
- [`subprocess.Popen()`]()

### Additional context
The pager should work on Linux, MacOS and Windows

**Comment by mr-tz** [comment]
It's an interesting idea. Why did you reconsider and close this?

**Comment by s-ff** [comment]
Hi @mr-tz ,

I realized https://github.com/mandiant/capa/issues/1686#issuecomment-1667626860 had already discussed the issue. So I didn't want to create a duplicate. Do you recommend reopening the issue :) ?

**Comment by mr-tz** [comment]
Ah, yeah, that's good then. Thanks!
