### ISSUE TITLE
dotnet: yield FORMAT_DOTNET before FORMAT_PE when processing .NET files

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2022]
We should change the order used to yield multiple formats for .NET files so `FORMAT_DOTNET` is used for capa's output metadata.

https://github.com/mandiant/capa/blob/49231366f1cbb800f296c60a2cb99f97466e2e33/capa/features/extractors/dotnetfile.py#L51-L53

This order doesn't matter for matching but does matter when collecting the file's metadata because we default to the first in the list

https://github.com/mandiant/capa/blob/49231366f1cbb800f296c60a2cb99f97466e2e33/capa/loader.py#L385-L387

**Comment by mr-tz** [comment]
Alternatively, display all formats.

**Comment by samadpls** [comment]
Hi @mr-tz , can i take this issue :)

**Comment by mr-tz** [comment]
of course
