### ISSUE TITLE
Control flow obfuscation causing basic block to be missed

### ISSUE THREAD

**Issue by re-fox** [mandiant/capa#203]
### Description
This issue may be for vivisect, but it appears that some control flow obfuscation is (I assume) causing a basic block to be missed.  I've posted up my notes below for troubleshooting.

### Steps to Reproduce
1. Run Capa with the following rule, against the attached binary 
[329b3ddbf1c00b7767f0ec39b90eb9f4f8bd98ace60e2f6b6fbfb9adf25e3ef9.zip](https://github.com/fireeye/capa/files/4974802/329b3ddbf1c00b7767f0ec39b90eb9f4f8bd98ace60e2f6b6fbfb9adf25e3ef9.zip)  (Password `infected`)

```
rule:
  meta:
    name: foo
    namespace: bar
    scope: basic block
  features:
    - and:
      - api: SystemParametersInfoW
```

**Expected behavior:**
Rule should trigger on the basic block located at `00406A84`

**Actual behavior:**
Does not trigger on the expected rule

### Versions
Built from `master`

### Additional Information
This is where results are inconsistent across tools.  

#### According to Cutter:
Cutter will see the basic block and the call to `SystemParametersInfoW`, cross referencing back shows the function starts at `0x004061d1`.   

Searching for the import:
![image](https://user-images.githubusercontent.com/57954766/88447162-4d455c80-cdfe-11ea-8da5-19e031417119.png)
Checking xrefs
![image](https://user-images.githubusercontent.com/57954766/88447182-6d751b80-cdfe-11ea-8463-2ff25a71c32b.png)

#### According to Ghidra:
Ghidra sees the import, but no xrefs.
![image](https://user-images.githubusercontent.com/57954766/88447217-bb8a1f00-cdfe-11ea-9d60-e522b92cbe1f.png)

Browsing to the function, it's easy to see where the disassembler becomes confused and parsing stops.
![image](https://user-images.githubusercontent.com/57954766/88447313-e628a780-cdff-11ea-94bc-006327e9cf37.png)

#### According to BinaryNinja:
BinaryNinja sees the beginning of the function as `0x004061d1`.  Disassembly will eventually fall to the basic block that contains the API call.
![image](https://user-images.githubusercontent.com/57954766/88447415-0c027c00-ce01-11ea-947c-98473f0c27cc.png)

The basic block:
![image](https://user-images.githubusercontent.com/57954766/88447504-03f70c00-ce02-11ea-8039-1e9d77e29480.png)

**Comment by williballenthin** [comment]
i'll triage this, maybe on monday or tuesday. unfortunately, we're at the whim of the underlying analysis engine, so unless there's a quick fix, we may just have to accept it.

yesterday, i noticed a bunch of FNs due to viv not finding functions, too.

**Comment by williballenthin** [comment]
getting a ghidra plugin working is pretty high on my priority list (especially adding py3 ;-) ), and i know @psifertex is actively working on BN. so, we'll soon have a pretty comprehensive set of backends from which you can pick your favorite.

**Comment by psifertex** [comment]
Yup! Seeing this maybe I'll prioritize the backend as opposed to the UI though the true CLI version of capa will only work via a commercial headless license. Using capa as a library in the BN Python repl would still work in personal, but I'm still wrapping my head around the current capa architecture a bit.

RE: Py3 and Ghidra, those are mutually exclusive though, no? I think jython still has no python3 support.

**Comment by re-fox** [comment]
Thanks for the comments, looking forward to more analysis backends.  

In Ghidra, Radare, and BinaryNinja the analysis level can be adjusted.  Running aggressive function finders may result in some bad analysis, but it may also find functions that we not disassembled on the initial pass.  

BinaryNinja does some neat stuff with opaque predicate removal and simplifying control flow in their lifting.  If BN uses a lifted form of assembly, the only downside would be changes in mnemonics within signatures.  (This is probably a topic for another thread)

Does vivisect support varying levels of analysis?  If so, is this something that could be configured from Capa?

**Comment by williballenthin** [comment]
yeah, vivisect has a configurable set of analysis passes; however, i believe they're all enabled by default, so there's not a dial that we could turn further.

but, we could provide our own "aggressive function finder" when we initialize viv and maybe find more code. i think a function prologue scan would probably help, for instance.

**Comment by williballenthin** [comment]
in the sample originally provided by @re-fox, the function in question contains a good deal of anti-disassembly. for example:

![image](https://user-images.githubusercontent.com/156560/89241998-b32fa200-d5bd-11ea-8591-15dbb11472de.png)

(this is consistent with the screenshots above).

IDA is not able to tie the basic block back to a function, so I don't the IDA Pro plugin would work either (we currently go, `for each function: find capabilities`).

**Comment by mr-tz** [comment]
Closing this as we cannot do much based on the analysis issues in various backends here.
