### ISSUE TITLE
Use rich to replace tqdm, tabulate, termcolor, etc.

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2100]
> If we end up adopting rich, we could maybe use some of its other features to reduce dependencies, for example replacing tqdm with rich.progress and tabulate with rich.table. It could also serve to implement a pager functionality for long output texts.

rich was added in https://github.com/mandiant/capa/pull/2086

**Comment by Rana-KV** [comment]
@mr-tz, Is this task open for working? 
I'm interested to work on this issue

**Comment by mr-tz** [comment]
yes, please go ahead!

**Comment by s-ff** [comment]
Let's also replace `termcolor`.

**Comment by s-ff** [comment]
Hi @Rana-KV, are you still working on this issue?

**Comment by mr-tz** [comment]
Unassigned due to inactivity.
