### ISSUE TITLE
binexport: loop detection Ghidra-generated BinExport

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2101]
This doesn't appear to work for Ghidra-generated BinExport (see CI fails). This must be an issue with the BinExport files themselves as we don't calculate the back edges in capa. It's not clear where the issues lies in the BinExport file generation, specifically, if it's with the Ghidra extension or BinExport core. More investigation needed.

_Originally posted by @mike-hunhoff in https://github.com/mandiant/capa/pull/1950#discussion_r1613954246_
            

issue lies in the Ghidra extractor: google/binexport#131

**Comment by mike-hunhoff** [comment]
I looked into this on the BinExport side and did not find a clear path forward for implementation w/out additional input from the BinExport developers. I've fallen back in [798894a](https://github.com/mandiant/capa/pull/1950/commits/798894a475f80694f1fee06750dd26f8a3b57406) to loop detection that uses the same method as our other feature extractors (w/ a `#TODO` to update the code when the bug has been resolved in BinExport).

**Comment by mr-tz** [comment]
great, thanks!
