### ISSUE TITLE
binexport: fixture 687e79.be2 tight loop not matched

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2113]
see original comment: https://github.com/mandiant/capa/pull/1950/files/b578c4d052e8899e82e06dd948c8e7395f391cec#r1622150361

**Comment by mike-hunhoff** [comment]
@mr-tz I ran a test script and wasn't able to find any tight loops in the referenced sample. I was able to confirm that tight loops appear to work in other x86 / ARM samples. Therefore, this doesn't appear to be a bug but if you have a specific example of where this failed in the referenced sample we can reopen.

**Comment by mr-tz** [comment]
ha, yeah, good find, I've updated the tests in https://github.com/mandiant/capa/pull/1950/commits/fe2e80fb90c8807af6acf16e65f14c2ec995d871
