### ISSUE TITLE
webui: indicate number of matches per rule

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2159]
show how often a rule matched similar to capa explorer

**Comment by mr-tz** [comment]
@s-ff, I don't think order or filter by match count makes sense. Can we show this label right after the rule instead?

**Comment by s-ff** [comment]
> @s-ff, I don't think order or filter by match count makes sense. Can we show this label right after the rule instead?

Yeah sure, I can remove this column and have it displayed as label instead next to rules
