### ISSUE TITLE
webui: search/filter over rule names, namespaces, and features

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2160]
potentially others as well (MITRE/MBC or other meta data?)

filter out non-matching functions

highlight the matches features in applicable rules (and also show rest of the rule)

**Comment by mr-tz** [comment]
@s-ff, the filtering should work across the entire text / fuzzy match - right now it seems it only works if you type the correct start

**Comment by mr-tz** [comment]
For namespace we could consider adding/using a dropdown with the covered namespaces.

**Comment by s-ff** [comment]
> @s-ff, the filtering should work across the entire text / fuzzy match - right now it seems it only works if you type the correct start

I am aware of this, working on fixing it.

>For namespace we could consider adding/using a dropdown with the covered namespaces.

In that case, I think we can use a drop down menu with the root namespaces only.  Like this:
![Kapture 2024-07-02 at 13 53 57](https://github.com/mandiant/capa/assets/31004043/816393b9-32bd-4f7b-9311-9b7702bd7182)

**Comment by s-ff** [comment]
closed as completed. 

>For namespace we could consider adding/using a dropdown with the covered namespaces.

will create a task for this as a nice-to-have
