### ISSUE TITLE
webui: deciding on a development approach

### ISSUE THREAD

**Issue by s-ff** [mandiant/capa#2168]
I am creating this issue to address the two potential ways we can adopt in developing capa-webui.

As of now, we are not using any frameworks, and building the webui as a standalone static website. Though it is worth discussing how we should approach this issue: As capa progresses and evolves, new features outside the original scope are requested, some of the technology choices made at the beginning (now) could greatly affect development in the future.

I tried to approach this question as unbiased as possible. Here are my thoughts:

There are many benefits for not using a complex framework in a project such as this, as an example:
- Little to no chance of dependencies breaking
- Using native functions are often run quicker and loading times are almost instantaneous
- We reduce the learning curve as contributors don't have to learn a new framework before they can contribute and introduce new features
- We avoid depending on third party code that can become deprecated or no longer maintainable. 

On the other hand:
- Frameworks promote common structure to code, making it easier for new developers to pick up (given they have knowledge of the framework), as well as improving general maintainability, as opposed to custom code which might not generally follow a general structure
- Most importantly, reduces the "boilerplate" code (and styling) that surrounds a lot of native functions (we don't have to write code for creating buttons, sorting a table, pop-up and hover messages, dark mode functionality, and many more ... since this is already baked in to the framework)
- Better interaction between the HTML and the JS (callbacks, event handling, ... etc)
- Frameworks offer easier ways to implement unit tests for the project
- We can re-use the same technology for other projects (capa-rules website?)

I am curious to hear your thoughts on this as well.

---
Unrelated to the webui, here is how Elastic organize their [detection-rules](https://elastic.github.io/detection-rules-explorer/), which could be a good base for capa-rules.

**Comment by williballenthin** [comment]
Many frameworks also require a build step, and package manager, and bundler. It can be a fair amount of configuration. All of it serves a purpose but it's also a lot of context for a maintainer to keep track of.

**Comment by mr-tz** [comment]
We've discussed this further today and are settling on using Vue.js (PrimeVue).
