### ISSUE TITLE
webui: show match location for multiple matches

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2189]
like done in capa explorer, we'll have to discuss if the actual address (function or basic block) is helpful or if we want to show something else (e.g. function 1, etc.)

![Screenshot from 2024-07-02 13-34-32](https://github.com/mandiant/capa/assets/17606537/acfe0210-2f13-4f3e-8a2b-f9562cf642d2)

**Comment by s-ff** [comment]
Completed.
