### ISSUE TITLE
webui: verify version of JSON result document

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2190]
let's pick a minimum we want to support and ensure users get notified if the requirement is not met

**Comment by s-ff** [comment]
We decided on supporting a minimum of version `7.0.0`, anything below will result in a error message explaining the unsupported version number. 

<details><summary>Also, I have changed the template of error/info messages to be more visible.

</summary>

![Kapture 2024-07-09 at 19 34 19](https://github.com/mandiant/capa/assets/31004043/52bf35ab-5e3f-4e8d-b694-84c75216d6da)

</details>
