### ISSUE TITLE
Consider a different name other than "Program properties"

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2194]
Consider a different name other than "Program properties" which may be misleading/confusing as some of the information e.g. Timestamp, Version, Extractor are specific to the capa analysis file. Maybe it can be removed all together to save space?

Suggestions:
- Analysis Information or
- Meta Information

**Comment by s-ff** [comment]
This wording has been removed. Though, the toggable panel to show the metadata has no label. 

I am closing this issue, because https://github.com/mandiant/capa/issues/2196 already deals with how we could better visualize the metadata.
