### ISSUE TITLE
webui: deep link to VT search

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2204]
When a user encounters an interesting rule match, they may want to pivot and find other samples that have that same behavior (especially if the rule is globally not-prevalent/interesting). We should provide a convenient button/link that jumps directly into a VT search for samples with that capa rule match. (We should also provide similar links to other services that expose capa rule matches, but I'm not aware of (m)any.) 

The search should open up in a new tab, if possible, so as not to disturb the current UI.

**Comment by williballenthin** [comment]
an example search URL is:
https://www.virustotal.com/gui/search/behaviour_signature%253A%2522act%2520as%2520Office%2520COM%2520add-in%2522/files

(which appears to be `urlencode(urlencode(behaviour_signature:"act as Office COM add-in"))` )

**Comment by s-ff** [comment]
Completed. Feel free to re-open this issue if the link is incorrect.

**Comment by mr-tz** [comment]
looks great!
