### ISSUE TITLE
webui: dynamic: collapse process / parent ID into process name when displaying matches by process

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2206]
e.g.
![Screenshot from 2024-07-11 13-40-41](https://github.com/user-attachments/assets/31d3749b-c86f-43c3-9bf5-936efcf5d6b4)

**Comment by mike-hunhoff** [comment]
I'm not sure the existing `PID/PPID` column will be of much use to users and removing would tighten up the UI. Open to discussion

**Comment by s-ff** [comment]
This is completed.
