### ISSUE TITLE
webui: tighten cell padding to save space

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2207]
e.g., as-is:
![Screenshot from 2024-07-11 13-45-50](https://github.com/user-attachments/assets/7829728c-78b7-4593-a66a-df4b678630d8)

**Comment by s-ff** [comment]
Row spacing is now compact

**Comment by s-ff** [comment]
Row spacing is now _very_ compact and the indentation has been reduced.

 ![grafik](https://github.com/user-attachments/assets/c4b63b85-db58-4011-9902-e5fecc37c836)
