### ISSUE TITLE
webui: condense "Show capabilities by process" view

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2213]
- [x] Set max length for process name (may need to play with this value a bit)
- [x] Split process ID  and parent process ID into separate columns
- [x] Remove `rule:` from matched rule display
- [x] Condense match count info e.g. `4 unique rules matches` to `4 unique matches` and `thread scope, 1 matches` to `1 thread match`
- [ ] Enable users to add/remove columns like the other views

Implementing the above should end up looking something like this:
![Screenshot from 2024-07-19 10-15-50](https://github.com/user-attachments/assets/2618a371-163d-40ca-9cf2-268f2a29649c)

**Comment by mike-hunhoff** [comment]
Maybe initially sort matches by rule name?

**Comment by s-ff** [comment]
Great feedback here! I will implement the changes and update this issue accordingly.

(when looking at this view, I am also particulary intrested in knowing what spawned what, so maybe a small parent-child process tree can help visualize)

**Comment by s-ff** [comment]
For now I added some visual color cues and sorting by PPID by default, the is the simplest option imho.

![grafik](https://github.com/user-attachments/assets/9a18e662-b0be-4d80-9b07-788ebf39b2af)

**Comment by williballenthin** [comment]
Initially I was imagining having the process tree interspersed with the rule results, but I like the above idea more: to have a small process tree at the top. 

Then maybe upon hover of nodes in the tree, the rules that match could be highlighted? Maybe also process checkboxes mute/highlight the rule entries that match (so this can be used on mobile). 

Hover could go the other way too: as a rule is hovered, the matching processes in the tree can be mute/highlighted. 

On a narrow display, the tree could go first. On a wide display, the tree could be laid out to the left of the rule matches. I'd imagine it doesn't need to be more than a few hundred pixels.

**Comment by s-ff** [comment]
We can create a minimal horizontal process tree and have the process nodes display a tooltip with the matched capabilities. See a small preview [here](https://codepen.io/Soufiane-Fariss/full/vYqKYoY) which uses D3.js, which I adopted from: https://gist.github.com/d3noob/9692795

**Comment by williballenthin** [comment]
Please start with the vertical layout since (I think) it can reuse the libraries we're already using for tree rendering/collapsing.

**Comment by mr-tz** [comment]
I agree that a simple vertical layout suffices, like process explorer: https://upload.wikimedia.org/wikipedia/en/7/77/Process_Explorer_Screenshot.png

**Comment by s-ff** [comment]
> I agree that a simple vertical layout suffices, like process explorer: https://upload.wikimedia.org/wikipedia/en/7/77/Process_Explorer_Screenshot.png

I've put together an implementation for this. Feel free to test it out. 

>  Enable users to add/remove columns like the other views

Do we still want to implement this? This issue https://github.com/mandiant/capa/issues/2215 recommends removing this option in all views.

**Comment by mr-tz** [comment]
> Enable users to add/remove columns like the other views

let's skip this
