### ISSUE TITLE
webui: simplify expert-mode tools

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2215]
I'd like to propose the following tweaks to the existing UI, in order to simplify and focus on the rule match content. This should also enable the removal of some code/maintenance.

Remove "Toggle All" button, since only a single row should be expanded at any point in time:
![image](https://github.com/user-attachments/assets/4a4f2f6a-342c-413f-b1ae-70449ff5ddc9)

Remove (or hide display behind global preferences dialog) the column filter inputs with preference for global search:
![image](https://github.com/user-attachments/assets/ef017eb0-36f0-4c16-94a7-843061bae630)

Always show the columns (rule, namespace, ATT&CK, MBC) and remove configurability:
![image](https://github.com/user-attachments/assets/5b254752-fc4a-4766-978b-2484e15dba1d)
remove columns "Address" and "Source"

**Comment by williballenthin** [comment]
Good point that we'll need a few more links. I wonder if a dropdown of links is appropriate here, or maybe the links can be displayed as a list once an entry is expanded? 

I don't like the idea of having lots of extra columns. I could probably be persuaded on icons, though I don't super like how they're be repeated on every line.

**Comment by mr-tz** [comment]
Ah neat, I'd like to see the drop-down as a first pass maybe using ... to hide the links.

**Comment by williballenthin** [comment]
during our sync today, @s-ff showed how to display a right click menu that may work well for this. he'll explore this, with the backup plan of a dropdown list or entry details element.

**Comment by s-ff** [comment]
> during our sync today, @s-ff showed how to display a right click menu that may work well for this. he'll explore this, with the backup plan of a dropdown list or entry details element.

I was able to get this to work, I will implement it now. It should look like:
![grafik](https://github.com/user-attachments/assets/d89eef6c-3133-4a6a-bc1e-9545e578dd04)
_(correct if I am wrong on the links here)_

**Comment by mr-tz** [comment]
That looks promising! Can you add icons in there as well (easily)?

**Comment by mr-tz** [comment]
And does this prevent copying highlighted text or other functionality via the regular browser right-click menu?

**Comment by s-ff** [comment]
<details><summary>Adding icons should be easy to do, though I received feedback that we should avoid icons as much as possible.</summary>

![grafik](https://github.com/user-attachments/assets/da8bcbe8-20ba-4fdd-a218-16842cc43a66)
</details>



----
> And does this prevent copying highlighted text or other functionality via the regular browser right-click menu?

The default browser right-click won't be available, but selecting, copying and pasting text via CTRL+C works fine.

**Comment by s-ff** [comment]
- [X] Context menu right click implemented (only) for rule title and `- match:` statement.
- [X] remove toggle all button
- [X] make row click event expand the the rule match
- [X] remove table column configurability
