### ISSUE TITLE
webui: add links to external resources

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2216]
Link to ATT&CK framework definitions:
![image](https://github.com/user-attachments/assets/a8f294e0-0b79-4ecc-b291-be5cf66550f0)

Link to MBC catalog entries:
![image](https://github.com/user-attachments/assets/d030febf-2c74-4287-93c1-6819eda35ef1)

Link to capa rule website entries (final URL pending, insert placeholder value for now):
![image](https://github.com/user-attachments/assets/285a4b0b-1fa4-4dcb-bf94-d05e0ed74fe7)
(and remove "source" column)

Link SHA256 to VirusTotal:
![image](https://github.com/user-attachments/assets/0819d99c-70c8-4915-98f3-d791cf442951)

also #2204

**Comment by s-ff** [comment]
>Link to ATT&CK framework definitions

@williballenthin MITRE ATT@CK TTPs alreay link to the MITRE project?

**Comment by williballenthin** [comment]
ATT&CK, yes (my apologies), MBC no.

Lets add an underline on hover (or other indicator) so that it's obvious that these are links. I didn't realize this until I tried to click the data.

**Comment by s-ff** [comment]
>Lets add an underline on hover (or other indicator) so that it's obvious that these are links. I didn't realize this until I tried to click the data.

There is already a cursor pointer on hover, I will try to maybe highlight the links with blue color to indicate they are clickable.

**Comment by mr-tz** [comment]
I'm not sure if the links from the rule title to the repo are the most intuitive/user-friendly. I'd prefer a separate icon (as implemented currently) to show the full rule content and (another one) to link to the repo.

I'd expect that clicking the rule name in this view would expand the details (like clicking on the `>` now).

**Comment by s-ff** [comment]
I agree with @mr-tz here, I think having the rules titles clickable will cause a lot of misclicks when trying to expand a tree node resulting in accidental redirects to capa-rules which is not a good UX. 

> I'd expect that clicking the rule name in this view would expand the details (like clicking on the > now).

I thought of this as well. It is not built-in, and needs to be manually implemented.

**Comment by s-ff** [comment]
@williballenthin 
> Link SHA256 to VirusTotal

I am thinking of adding a small VT icon next to the hash, maybe also include hybrid-analysis, OPSWAT Metadefender? Once clicked they will respectively pivot to:
```
www.virustotal.com/gui/file/<SHA256>
www.hybrid-analysis.com/sample/<SHA256>
https://metadefender.opswat.com/results/file/<sha256>/hash/multiscan
```

**Comment by mr-tz** [comment]
> @williballenthin 
> 
> > Link SHA256 to VirusTotal
> 
> 
> 
> I am thinking of adding a small VT icon next to the hash, maybe also include hybrid-analysis, OPSWAT Metadefender? Once clicked they will respectively pivot to:
> 
> ```
> 
> www.virustotal.com/gui/file/<SHA256>
> 
> www.hybrid-analysis.com/sample/<SHA256>
> 
> https://metadefender.opswat.com/results/file/<sha256>/hash/multiscan
> 
> ```

Let's not link to other 3rd party sites for now.

**Comment by s-ff** [comment]
MBC, ATT@CK and SHA256 now redirect to external resources. 

Toggling the node when the title is clicked will be added to the tracker as P2.

Closed as completed.
