### ISSUE TITLE
webui: flesh out main page text

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2219]
Draft and finalize all the text and content that goes here:
![image](https://github.com/user-attachments/assets/0561913c-9abe-459c-ae41-5f0808283ab7)

Move the content of this dropdown into the landing page:
![image](https://github.com/user-attachments/assets/ae59df45-0333-47f2-a1df-1061dedb8be4)

**Comment by mr-tz** [comment]
I don't see links to other repos/tools as relevant here so would remove it all together?!

**Comment by mike-hunhoff** [comment]
> I don't see links to other repos/tools as relevant here so would remove it all together?!

Agreed, I don't think this is needed

**Comment by s-ff** [comment]
Removed toolset menu as dicussed above.

----

> @s-ff do you want to task me / @mr-tz / @mike-hunhoff with drafting the text and opening a PR against your app? If so, would you walk us through what that looks like?

That's would be great, a simple sketch and draft text of the landing page would be enough.
