### ISSUE TITLE
webui: release process

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2251]
The initial webui is almost ready for release. One thing we still need to figure out is how and where we want to distribute the standalone HTML (single-page application SPA).
In my opinion the online webui will always be served directly from the `webui` directory (so whenever we merge code there, the page will reflect that).

1. How will SPA releases be created - automatic on merge vs. manual triggered workflow?
2. Do we include the SPA in the standalone and Python distributions? See https://github.com/mandiant/capa/issues/2183
3. Where do we store releases? E.g. `webui/releases/capa-webui-<datestring>.html`
4. Do we want to include the SPA HTML in the capa releases (https://github.com/mandiant/capa/releases)
  a. if so, do we just link to the release storage path
  b. or do we add/update the HTML to releases (this can get complicated quickly)

Edit:
- [x] #2257
- we really only need to keep older webui versions around if there's compatibility issues with newer capa releases

**Comment by s-ff** [comment]
Coming back to this, I believe maintaining older versions of capa explorer web is unnecessary. The latest release ensures backward compatibility with capa JSON outputs version 7.0.0 and later.


>1. How will SPA releases be created - automatic on merge vs. manual triggered workflow?

The release (`capa-explorer-web.zip`) will be automatically generated on each run of `web-deploy.yml`.

>2. Do we include the SPA in the standalone and Python distributions? 

I don't have a strong opinion on this to be honest.

>3. Where do we store releases? E.g. webui/releases/capa-webui-<datestring>.html

capa releases will be stored in the Github Pages deployed instance. Users can navigate to the website to download the offline release.

>4. Do we want to include the SPA HTML in the capa releases 

I prefer keeping the capa core releases seperate from the web releases, esp. when we don't need to keep old versions after each build

**Comment by mr-tz** [comment]
Sounds great. I think we can close this here. For https://github.com/mandiant/capa/issues/2183 I'd like to at least add documentation/usage information.
