### ISSUE TITLE
add a download link to the online version that points to the latest SPA HTML release

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2257]
Similar to CyberChef: "Download capa Web Explorer" towards the top of the page

**Comment by s-ff** [comment]
I belive this simplifies the process and also makes sure that the latest build is always available via the website for download. We could add a build step (`npm run build:bundle`) to [`web-deploy.yml`](https://github.com/mandiant/capa/blob/master/.github/workflows/web-deploy.yml) and store the .zip artifact for download by users.
