### ISSUE TITLE
decide on name for webui and make consistent throughout project

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2272]
general comment: we need to figure out and be consistent with what we're calling this thing.

some options:
  - capa web explorer
  - capa explorer web
  - capa explorer web application
  - web capa explorer
  - capachef

once we've decided, we should go back through all the source code and make things consistent.

_Originally posted by @williballenthin in https://github.com/mandiant/capa/pull/2258#discussion_r1712126810_

**Comment by binjo** [comment]
capachef sounds cool 🙌

**Comment by williballenthin** [comment]
I sorta prefer "capa explorer web application" or "capa explorer web" because then we can call the IDA integration "capa explorer IDA plugin" or "capa explorer IDA" which has nice symmetry.

**Comment by mr-tz** [comment]
My preference is "capa web explorer" but the symmetry in naming makes sense to me. So, I guess the proper name is "capa explorer" and by context one can infer what's meant (IDA vs. web, etc.).

**Comment by mike-hunhoff** [comment]
Name symmetry is top of mind because IMO this will help avoid confusion e.g.:

"capa explorer [for] web"
"capa explorer [for] IDA"
"capa explorer [for] Ghidra"
"capa explorer [for] Binary Ninja"
...

v.

"capachef"
"capa explorer"
"capa Ghidra explorer"
"capa Ninja"
...

**Comment by mr-tz** [comment]
I think we've settled on `capa explorer ...` so let's rename all instances for the webui to `capa explorer web` (all lower case).
