### ISSUE TITLE
webui: dynamic preview button does not work

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2285]
error:

```
Unsupported Version
Version 6.1.0 is not supported. Please use version 7.0.0 or higher.
```

**Comment by mr-tz** [comment]
blocked by https://github.com/mandiant/capa-testfiles/pull/245

**Comment by mr-tz** [comment]
we can use https://github.com/mandiant/capa-testfiles/blob/master/rd/0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.json.gz now
