### ISSUE TITLE
webui: no obvious path back to initial landing page after loading capa analysis

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2286]
e.g. clicking "preview static" navigates to the analysis page, with on obvious means to return to the upload page, and using the back button unexpectedly navigates to GitHub (where original link was followed).

**Comment by mike-hunhoff** [comment]
An option here would be allowing users to click the upper right capa logo to navigate back to the initial upload page.

**Comment by mr-tz** [comment]
Also IMHO move icons from top right to the top left.
