### ISSUE TITLE
webui: not obvious that entries can be expanded for initial static capabilities view

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2287]
![Screenshot from 2024-08-13 08-26-11](https://github.com/user-attachments/assets/1a5cf9b6-e314-48cf-a9b2-3a0dc7f8ae93)

should be something like

![Screenshot from 2024-08-13 08-28-36](https://github.com/user-attachments/assets/835d055b-e61c-42e0-b64e-b4992a4005e4)

**Comment by mr-tz** [comment]
agree that it makes sense to re-add the `>` symbols

**Comment by s-ff** [comment]
There is a bug in the UI library when combining both clicking the row and the toggle icon for which I have filed a bug report. Only one of them can work at a time. For now, I prefer removing `>` toggle icon in favor of clicking the row to expand it until this is fixed.

**Comment by williballenthin** [comment]
lets keep this issue open while it affects our application. perhaps there are other ways we could fix our issue?

**Comment by williballenthin** [comment]
for example, we could provide our own icon and change its orientation while the details are expanded. i think a couple lines of CSS should do it. no need to rely on the UI framework for this. would you like me to take a stab?

**Comment by mr-tz** [comment]
I think it's fine for now if the click on the icon does not also expand the first child.

**Comment by s-ff** [comment]
> for example, we could provide our own icon and change its orientation while the details are expanded. i think a couple lines of CSS should do it. no need to rely on the UI framework for this. would you like me to take a stab?

That's a reasonable approach, another easy way to do this would be to disable the button behavior (but keep it shown) and clicking on it would be considered as a row click instead of a button click. will research this a bit more.
