### ISSUE TITLE
Failed to load plugin on IDA9.0

### ISSUE THREAD

**Issue by yinsel** [mandiant/capa#2311]
### Steps to Reproduce

**Expected behavior:**

Successfully loaded plugin on IDA9.0

**Actual behavior:**

Failed to load plugin on IDA9.0

**Comment by mr-tz** [comment]
Thanks, there's likely a few updates we'll have to make to the plugin/scripts.

**Comment by yinsel** [comment]
> Thanks, there's likely a few updates we'll have to make to the plugin/scripts.

ok😀

**Comment by yinsel** [comment]
> 谢谢，我们可能必须对插件/脚本进行一些更新。

Copy 'capa-explorer.py' to the plugin directory, but IDA9.0 still cannot find the option.

**Comment by yinsel** [comment]
> 您是否更新到 master 中的代码？

yes

**Comment by mr-tz** [comment]
Can you please detail your steps and the issue? I just tried again and it works for me.
