### ISSUE TITLE
vverbose output duplicates some lines, sometimes

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2323]
it seems that the vverbose output mode duplicates some lines, sometimes. see this screenshot when running against PMA 01-01:

![Screenshot 2024-08-22 11 09 15 AM](https://github.com/user-attachments/assets/f9260192-56d9-45c6-af6c-abc2698f4bb2)

**Comment by williballenthin** [comment]
the result document has multiple entries:
![image](https://github.com/user-attachments/assets/03e1d3b9-6ba6-4066-8ab5-d9c53d2a72b9)

so its not that vverbose is wrong, the result document has duplicates.

**Comment by williballenthin** [comment]
this comes from the rule:
![image](https://github.com/user-attachments/assets/8b1cb9be-61b7-4a8a-9294-40efaef89173)

and the fact that we trim the DLL name from API features:

![image](https://github.com/user-attachments/assets/a8eb1434-c402-484a-abb3-b4e1ed7f0e32)

so we end up with logic that looks like:

```yml
- or:
  - api: recv
  - api: recv
```

which is correctly matched and rendered.

to fix, we should deduplicate these features that the rule wants to match.

**Comment by williballenthin** [comment]
the trimming was introduced here: https://github.com/mandiant/capa/commit/c9df78252a19891cc9a12cf85bf20ed0153e2bc4
#1824 and #1815

**Comment by s-ff** [comment]
Yeah, I noticed this as well while working on explorer:

Example: the first 2 socket `api` statements in "create TCP socket": https://mandiant.github.io/capa/explorer/#/?rdoc=https://raw.githubusercontent.com/mandiant/capa-testfiles/master/rd/0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.json.gz


![image](https://github.com/user-attachments/assets/f40fb2ba-59d6-4fa7-b332-01d544ce6237)
