### ISSUE TITLE
add links from CLI output to capa rules website

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2337]
we can use a modern terminal feature to make some text a link to a URL, such as described here: https://www.willmcgugan.com/blog/tech/post/real-working-hyperlinks-in-the-terminal-with-rich/

So, for example, each rule name in the default output could be a link to the rules website, showing the rule content.

I think that for terminals that don't support this feature, the link degrades to text, just like is shown today.

The `rich` library that we use for rendering already has a link feature that we can use here.

**Comment by williballenthin** [comment]
if/when we show global prevalence information, those terms could link to VT searches.

**Comment by williballenthin** [comment]
link to ATT&CK and MBC pages

**Comment by williballenthin** [comment]
make references clickable

**Comment by williballenthin** [comment]
![image](https://github.com/user-attachments/assets/84ff1a21-3fb4-4b23-b661-7b46aa63ce38)

**Comment by williballenthin** [comment]
![image](https://github.com/user-attachments/assets/ea4dc2f4-f870-49f1-8d83-b133f1504958)

**Comment by s-ff** [comment]
Does this feature work with all terminal emulators? I imagine only modern consoles to support this

**Comment by williballenthin** [comment]
Yeah, when unsupported, then the text falls back to how it's shown today. And I don't think there's logic that does this - the terminal emulator just ignores the control codes it doesn't understand.

**Comment by williballenthin** [comment]
It doesn't work under tmux but does under zellij and xterm. i can test Windows Thermal Terminal later today.
