### ISSUE TITLE
linter: ERROR:capa:[Errno 2] No such file or directory: 'capa/rules/__init__.py'

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2350]
```
ERROR:capa:[Errno 2] No such file or directory: 'capa/rules/__init__.py'
```

see e.g. https://github.com/mandiant/capa-rules/actions/runs/10724056570/job/29870040135

**Comment by mr-tz** [comment]
@williballenthin, do you have an idea what changed resulting in these errors?

**Comment by williballenthin** [comment]
I'll take a look in a few minutes

**Comment by williballenthin** [comment]
https://github.com/mandiant/capa/blob/7b101b33dcbde5b53814e7d33a4d38e7d842adad/capa/helpers.py#L355

this line hardcodes the relative location of some source files, and the linter is run from `./rules/` so the source files don't exist. the fix is to use the actual source file path. i'll open a PR.
