### ISSUE TITLE
new point release

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2424]
if we do a point release soon (which I think we were planning to do), then lets include a note about this (and maybe warning when run under Python 3.8 or 3.9). then as soon as that's released, bump the minimum python version to 3.10 and start using those language features.

thoughts?

_Originally posted by @williballenthin in https://github.com/mandiant/capa/issues/1966#issuecomment-2385957492_

**Comment by mike-hunhoff** [comment]
+1 for a point release, we've recently merged some bug fixes for the dynamic backends that would be good to push to our users.
