### ISSUE TITLE
capa explorer web: no horizontal scroll when viewing long entries

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2434]
There is no horizontal scroll when expanding long entries, which makes viewing the corresponding columns impossible. This issue was experienced in Chrome, not sure if specific to this browser or not.

e.g. 
![Screenshot from 2024-10-02 11-24-08](https://github.com/user-attachments/assets/05557c0e-1d0b-42c0-9db2-65ed39061c51)

The above is from the example dynamic view linked from the web interface.

**Comment by mike-hunhoff** [comment]
Ideally, text wrapping should be used for cases like this.

**Comment by mike-hunhoff** [comment]
> Could you share the sample with me? I'll take a look.

It's the example dynamic sample linked from the web interface (preview dynamic)

**Comment by s-ff** [comment]
<details><summary>
Seems to work for me (I am on Firefox). I'll implement text wrapping.
</summary>
<br>

![Kapture 2024-10-02 at 19 53 41](https://github.com/user-attachments/assets/98c40a29-2ac0-4346-98da-30fa14acc2fa)

</details>

**Comment by s-ff** [comment]
Let me know if this word wrap fix works for you: http://localhost:5173/#/analysis?rdoc=https://raw.githubusercontent.com/mandiant/capa-testfiles/master/rd/0000a65749f5902c4d82ffa701198038f0b4870b00a27cfca109f8f933476d82.json.gz

**Comment by mr-tz** [comment]
I don't see the original issue either, however I like the improvement with the word wrap regardless.
