### ISSUE TITLE
idaapi python module

### ISSUE THREAD

**Issue by D3vil0p3r** [mandiant/capa#2456]
I am trying to build from source and I see that capa uses idaapi module. I cannot use `pip` because I am packaging for Arch, but I cannot see where `idaapi` module can be retrieved. I checked on PyPI but there is no a dedicated module. Do you know how can I get it?

**Comment by D3vil0p3r** [comment]
To have it, in Arch Linux should I install [ida-pro](https://aur.archlinux.org/packages/ida-pro) package?

**Comment by williballenthin** [comment]
it's not a freely available module and it can't be used outside the IDA Pro scripting environment. if possible, you should ignore this import (which only happens when capa recognizes it's running within IDA).

**Comment by D3vil0p3r** [comment]
I see that `ida_netnode` lib depends on idaapi... so netnode is only used in that case too?

**Comment by williballenthin** [comment]
correct, netnode is an IDA Pro abstraction and also only relevant when running as a plugin.

**Comment by D3vil0p3r** [comment]
Ida Free is impacted by these mentioned IDA modules if I run it and capa?

**Comment by williballenthin** [comment]
IDA Free doesn't have Python scripting

https://hex-rays.com/pricing?section=individuals
