### ISSUE TITLE
CAPE extractor broken

### ISSUE THREAD

**Issue by xiangchen96** [mandiant/capa#2466]
### Description

Looks like I broke the CAPE extractor:
https://github.com/mandiant/capa/blob/master/capa/features/extractors/cape/models.py#L301
Could this be a flexiblemodel?

Source:
https://github.com/kevoreilly/CAPEv2/pull/2199#issuecomment-2414668108

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

**Comment by Hamzah1369** [comment]
Nice

**Comment by mr-tz** [comment]
Thanks for the heads-up @xiangchen96!
