### ISSUE TITLE
webui: "Lookup rule in VirusTotal" results in VT error "Unbalanced modifier or operator"

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2483]
e.g. "Lookup rule in VirusTotal" for the capa rule named `packaged as single-file .NET application` results in the VT search modifier `behaviour_signature:"packaged as single-file .NET application"` which results in the VT error `Unbalanced modifier or operator`. Manually changing the VT search modifier to `behaviour:"packaged as single-file .NET application"` produces the desired result.

**Comment by fariss** [comment]
Not sure if VT has changed the search query from `behaviour_signature` to `behaviour`. Last time I checked it was behaviour_signature that was to lookup capa matches (https://github.com/mandiant/capa/issues/2204).

**Comment by mike-hunhoff** [comment]
@fariss I reached out to the VT team and this issue has been fixed. There is no action needed on our end, thank you!
