### ISSUE TITLE
IDA 9 bin_search3 name change

### ISSUE THREAD

**Issue by phate1** [mandiant/capa#2497]
### Description
in IDA version 9
`ida_bytes` `bin_search3` became `bin_search` as in this:
[Commit 22368fb](https://github.com/mandiant/capa/commit/22368fbe6f4d79479bfff6614f10ad3cc6e16848) 
which isn't in the release, causing it to crash on IDA9

### Steps to Reproduce

pip install flare-capa
capa --version (capa 7.4.0)
run plugin in in IDA9

**Expected behavior:**

lots of lovely matches

**Actual behavior:**

ida_bytes' has no attribute 'bin_search3'

### Versions
CAPA 7.4.0
IDA 9
python3 3.10
windows11

**Comment by mr-tz** [comment]
Yes, we need a new release to have the fix available.

**Comment by Still34** [comment]
It looks like this hasn't been fixed in v8.0.0 release?

**Comment by mr-tz** [comment]
Can you try with 8.0.1 please?

**Comment by Still34** [comment]
> Can you try with 8.0.1 please?

Ah yes, fixed in v8.0.1. Sorry for not checking!

**Comment by mr-tz** [comment]
Thanks for confirming!
