### ISSUE TITLE
binja unit test failing because an expected function is not created by the auto analysis

### ISSUE THREAD

**Issue by xusheng6** [mandiant/capa#2507]
The binja unit test is now failing: https://github.com/mandiant/capa/actions/runs/12018561216/job/33504909578#step:7:222

And the reason is the stable 4.2 binja is not creating a function at 0x14004b4f0 for the sample `al-khaser_x64.exe_`

![Screenshot 2024-11-26 at 1 54 32 PM](https://github.com/user-attachments/assets/8c51f10f-fb58-4b11-bba1-5af34f7494c2)

**Comment by xusheng6** [comment]
I will create an issue for it since a proper fix will only come in the next stable release

**Comment by xusheng6** [comment]
@williballenthin I checked the code and did not find a good way to workaround this. Can we disable the `al-khaser_x64.exe` test for binja backend? Since even if we have a proper fix for it soon, it would not be available in the stable until the next stable release

**Comment by xusheng6** [comment]
@williballenthin please add binary-ninja tag on this

**Comment by mr-tz** [comment]
Could we manually create the function like for vivisect?

https://github.com/mandiant/capa/blob/c85be8dc7200cb13a6b77bedaa1e97076e63109f/tests/fixtures.py#L119-L128

**Comment by xusheng6** [comment]
> Could we manually create the function like for vivisect?
> 
> https://github.com/mandiant/capa/blob/c85be8dc7200cb13a6b77bedaa1e97076e63109f/tests/fixtures.py#L119-L128
> 
> Otherwise, we can just skip/xfail the test with the missing function.

We definitely should! I was looking for a place to do it, but I cannot find an elegant place to plug it. But now I know how to do it
