### ISSUE TITLE
develop script to highlight the features that are not used during matching

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#331]
to bring light to capabilities for which we do not yet have rules, we should develop a script that highlights the features that have been extracted by capa and yet not used by any rule. these entries might be sorted (and maybe reversed) based on their frequency. for example:

```
$ python scripts/show-unused-features.py /tmp/suspicious.dll_

count  feature
-----  -------
1      api: ClearEventLog
1      api: RtlPushFrame
...    ...
1145   mnemonic: push
```

a rule author could review these features an decide "hey, we need to cover event log clearing!" and use this output as inspiration.

**Comment by williballenthin** [comment]
@cl3o will take a stab

**Comment by Aayush-Goel-04** [comment]
@williballenthin , I'd like to take a shot at this

**Comment by williballenthin** [comment]
@Aayush-Goel-04 go for it!
