### ISSUE TITLE
discussion: capa doesn't handle sandbox or API traces

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#48]
capa relies on analysis of code structures to identify patterns. this is similar to matching sequences of API calls or other events in a sandbox, but not exactly. right now, capa rules don't directly translate to identifying behaviors from sandbox or debugging output, but it seems like there's a lot of overlap. maybe we can find a way to re-use a lot of work we've done for the static analysis rules.

**Comment by musaabimran** [comment]
Hey, I am interested in this project. How can I get started with this?

**Comment by mr-tz** [comment]
This is a larger project. Are you interested in the context of GSoC?
If so, please see https://github.com/mandiant/flare-gsoc-2023/blob/main/doc/project-ideas.md#capa-capabilities-from-dynamic-analysis and https://github.com/mandiant/flare-gsoc-2023/blob/main/doc/contributor-guidance.md.

**Comment by musaabimran** [comment]
Yes, I am. So, should I send the proposal regarding my approach?

**Comment by mr-tz** [comment]
Yes, and please see the other steps we point out, i.e., the patch preparation.

**Comment by musaabimran** [comment]
Can you guide me more about the requirements and scope of the project and what are you looking in the contributor?

**Comment by 1nf3rn0-H** [comment]
Even I am interested, I'll send the proposal right away!

**Comment by 1nf3rn0-H** [comment]
Hey @mr-tz I am interested to work on [this](https://github.com/mandiant/flare-gsoc-2023/blob/main/doc/project-ideas.md#capa-capabilities-from-dynamic-analysis). I have prepared my GSoC proposal, can you review it once?

**Comment by mr-tz** [comment]
Great, yes, please share it with us in the respective GSOC repo discussion or via email. Ideally, use Google Docs or a similar tool so we can add comments.

**Comment by 1nf3rn0-H** [comment]
Alright, I have sent it over email, do check and review!

**Comment by williballenthin** [comment]
closed in v7 by @yelhamer
