### ISSUE TITLE
ci: tag released commit of capa rules instead of master

### ISSUE THREAD

**Issue by Ana06** [mandiant/capa#529]
### Description

The tag GitHub Action tags master in capa-rules, instead it could tag the capa-rules commit used in the release. This is normally not a problem because we keep capa-rules and master in capa in sync (as long as we don't merge new commits in capa-rules while the tag action is running). But it is a problem when releasing other branch.

Note that this can be fixed manually (by deleting the tag and creating a new one) if needed.

**Comment by williballenthin** [comment]
see discussion in #1006
