### ISSUE TITLE
file limitation: vmprotect

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#588]
776e44dcfbfe05c52ef35712fd7dd4797072b087
20520e5dc8847d74f35e6c466382fb0962e30a89
d70464726bc0c39076a2c1e699eba1cdb1926406
derived from #509

implement via #390 capa rule

**Comment by williballenthin** [comment]
1. [ ] add examples to "packed with VMProtect"

**Comment by mr-tz** [comment]
A couple of observations which we cannot currently model:
* section names are variable, but use common pattern `.<name>0` and `.<name>1`, e.g. `.cod0/1`, `.vmp0/1`, `.tmp0/1`
** model via regex on section names or other section flags (not investigated)
* imports look wild, often multiple references to the same DLLs e.g. kernel32 and user32
** combined with section details, could make for good detection, would require more work in the backend

Can we maybe just analyze the entry point code and a few called functions?

some patterns:
```asm
.vmp1:01DEF62E                   start proc near
.vmp1:01DEF62E
.vmp1:01DEF62E                   ; FUNCTION CHUNK AT .vmp1:016B0AD4 SIZE 0000001D BYTES
.vmp1:01DEF62E
.vmp1:01DEF62E 68 E2 70 F3 0E    push    0EF370E2h
.vmp1:01DEF633 E8 1C 77 DC FF    call    sub_1BB6D54
```

```asm
.cod1:01C36228                   start proc near
.cod1:01C36228 68 BC 09 80 07    push    78009BCh
.cod1:01C3622D E8 20 72 5D 00    call    sub_220D452
.cod1:01C36232 06                push    es
.cod1:01C36233 F0 C2 2F 2C       lock retn 2C2Fh
```

```asm
.tmp1:00000001407A8311                   start proc near
.tmp1:00000001407A8311
.tmp1:00000001407A8311                   ; FUNCTION CHUNK AT .tmp1:000000014078E267 SIZE 0000000A BYTES
.tmp1:00000001407A8311
.tmp1:00000001407A8311 EB 08             jmp     short loc_1407A831B
...
.tmp1:00000001407A831B E9 47 5F FE FF    jmp     loc_14078E267
...
.tmp1:000000014078E267 68 4C 23 EA 30    push    30EA234Ch
.tmp1:000000014078E26C E8 81 DD 51 00    call    sub_140CABFF2
```

**Comment by mr-tz** [comment]
vivisect is very very slow on processing these files otherwise

besides adding the used section names for the listed samples I don't see any easy identification possibilities.

thoughts on moving this to the next milestone?

**Comment by mr-tz** [comment]
moved to v2.1.0 milestone

**Comment by williballenthin** [comment]
i've been brainstorming this offline a bit but need to really sit down and look at the samples. i dont have any quick fixes in mind right now.
