### ISSUE TITLE
Use upstream version of Ana06/get-changed-files@v1.1 once released

### ISSUE THREAD

**Issue by Ana06** [mandiant/capa#589]
In https://github.com/fireeye/capa/pull/584 we started using [`Ana06/get-changed-files@v1.1`](https://github.com/Ana06/get-changed-files/compare/v1...v1.1) as [`jitterbit/get-changed-files@v1`](https://github.com/jitterbit/get-changed-files/tree/v1) doesn't support `pull_request_target` (which we needed to use for the changelog action) and the project didn't seem to be maintained anymore. It seems that there are now plans to release `jitterbit/get-changed-files`: https://github.com/jitterbit/get-changed-files/pull/27#issuecomment-850075624 and that it will include very similar changes to [`Ana06/get-changed-files@v1.1`](https://github.com/Ana06/get-changed-files/compare/v1...v1.1). We should update to use the community version if `jitterbit/get-changed-files` continues to be maintained and releases a new version. I am documenting this here so that we don't forget.

**Comment by mr-tz** [comment]
We're using Ana06's v2.2.0 now.
