### ISSUE TITLE
perf: investigate matching optimizations

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#602]
capa sometimes feels like its a slow program (though it does it a lot of work in this time!). we should investigate where it spends its time (and memory) optimize areas that provide meaningful performance boosts.

running capa+full ruleset against kernel32.dll takes 2:12 (132s) on my laptop, of which 1:53 (113s, or 85%) is spent matching. im using an existing .viv, so initial analysis is not captured here (and is also not something we can affect). 

restricting capa to match a single rule ("suspend thread") takes 35s total, of which 13s is spent matching.

this suggests that the matching routine is a very hot area of the program. if we made the matcher run faster, capa would feel much faster to users.

**Comment by williballenthin** [comment]
the core matching routine is `capa.engine.match` here: https://github.com/fireeye/capa/blob/8f1ce68e96619e22ea406ee4cee3595426102c31/capa/engine.py#L233-L265

`evaluate` resolves to various implementations, such as `capa.engine.And.evaluate` https://github.com/fireeye/capa/blob/8f1ce68e96619e22ea406ee4cee3595426102c31/capa/engine.py#L120-L130 or `capa.features.Feature.evaluate` https://github.com/fireeye/capa/blob/8f1ce68e96619e22ea406ee4cee3595426102c31/capa/features/__init__.py#L103-L104.

we might be able to make some tweaks to these implementations (less garbage, more direct lookups, cached things, etc.).

i think it might also be possible to make big improvements by doing less work: maybe we can interpret fewer rules or features if we know they'll never be used anywhere.

for example, we can pre-process all rules to figure out which rules use which feature. then, when inspecting a scope, we can interpret only the rules that have features found in the scope. it *might* be that we can ignore many rules in most scenarios. we should collect data that proves or refutes this idea.

alternatively, we might examine the tradeoffs of working "by-rule" versus "by-feature". today, we iterate "by-rule"; however, as we add more rules, we may end up with usually more rules than features. in this scenario, maybe we should interpret "by-feature" instead. again, more data is needed.

and, of course, we'll want to make sure we're not over-engineering too much. we want capa to be fast so users don't get bored; however, there's only so fast we can make a Python program. we need to remember that capa already does its job much faster than a human, so we should prioritize this work below features that extend capa's expressiveness and usefulness.

**Comment by williballenthin** [comment]
false start: i tried caching `capa.features.Feature.hash` https://github.com/fireeye/capa/blob/8f1ce68e96619e22ea406ee4cee3595426102c31/capa/features/__init__.py#L76-L77

but this didn't affect runtime much.

**Comment by mr-tz** [comment]
Some details via some simple debugging output I added on a very slow example binary (AutoIT). Although, capa's first pefile pass now mitigates analysis of this sample, it's still a valid test candidate in my opinion.

* all other functions ran for <1.0 seconds (`find_capabilites`)
* all other rules ran for <0.5 seconds (`match`)

```
$ capa tests/data/55d77ab16377a8a314982f723fcc6fae.exe_ -d -v
DEBUG:capa:format: pe, platform: windows, architecture: i386, number of functions: 2505
DEBUG:capa:find_capa: ran 1.33 seconds on 0x00402d1a (134 features)
DEBUG:capa:find_capa: ran 1.33 seconds on 0x004063a0 (170 features)
DEBUG:capa:find_capa: ran 1.12 seconds on 0x00406bec (201 features)
DEBUG:capa:find_capa: ran 6.01 seconds on 0x0040a000 (347 features)
DEBUG:capa:find_capa: ran 4.15 seconds on 0x0040ba60 (142 features)
DEBUG:capa:find_capa: ran 1.25 seconds on 0x0040c707 (307 features)
DEBUG:capa:find_capa: ran 1.04 seconds on 0x0040d6f0 (130 features)
DEBUG:capa:find_capa: ran 1.05 seconds on 0x0040d910 (117 features)
DEBUG:capa:find_capa: ran 4.57 seconds on 0x0040e800 (177 features)
DEBUG:capa:find_capa: ran 1.82 seconds on 0x0040fe40 (215 features)
DEBUG:capa:find_capa: ran 3.57 seconds on 0x00410b30 (389 features)
DEBUG:capa:find_capa: ran 2.98 seconds on 0x00414140 (235 features)
DEBUG:capa:find_capa: ran 23.09 seconds on 0x004149c0 (486 features)
DEBUG:capa:find_capa: ran 2.32 seconds on 0x0041649e (117 features)
DEBUG:capa:find_capa: ran 2.77 seconds on 0x00416843 (265 features)
DEBUG:capa:find_capa: ran 12.79 seconds on 0x0041710e (512 features)
DEBUG:capa:find_capa: ran 1.86 seconds on 0x004183c4 (189 features)
DEBUG:capa:find_capa: ran 1.74 seconds on 0x00418a0e (197 features)
DEBUG:capa:find_capa: ran 1.43 seconds on 0x0042040a (118 features)
DEBUG:capa:find_capa: ran 3.19 seconds on 0x0042e7ab (196 features)
DEBUG:capa:find_capa: ran 1.63 seconds on 0x00436522 (96 features)
DEBUG:capa:find_capa: ran 2.00 seconds on 0x00436a94 (96 features)
DEBUG:viv_utils.BasicBlock:instructions: Failed to disassemble: 0x4390eb: InvalidInstruction("'ffff8b45cc0fb74dc48b55c68b75cac1' at 0x4390eb")
DEBUG:capa:find_capa: ran 2.65 seconds on 0x00439157 (141 features)
DEBUG:capa:find_capa: ran 1.09 seconds on 0x0043cc36 (106 features)
DEBUG:capa:find_capa: ran 1.21 seconds on 0x00442e71 (116 features)
DEBUG:capa:find_capa: ran 1.37 seconds on 0x00443a89 (120 features)
DEBUG:capa:find_capa: ran 1.36 seconds on 0x00443a9e (120 features)
DEBUG:capa:find_capa: ran 1.14 seconds on 0x004576c5 (118 features)
DEBUG:capa:find_capa: ran 1.59 seconds on 0x0045d062 (183 features)
DEBUG:perf:    match: ran 0.62 seconds on 'create or open registry key' for 0x46000d
DEBUG:capa:find_capa: ran 1.14 seconds on 0x00471d09 (98 features)
DEBUG:capa:find_capa: ran 1.39 seconds on 0x00472083 (63 features)
DEBUG:capa:find_capa: ran 1.17 seconds on 0x0047b025 (60 features)
DEBUG:capa:find_capa: ran 1.36 seconds on 0x0048cdac (261 features)
DEBUG:capa:analyzed file and extracted 16777 features
DEBUG:perf:    match: ran 0.54 seconds on 'reference analysis tools strings' for 0x0 (file)
DEBUG:perf:    match: ran 0.54 seconds on 'reference anti-VM strings' for 0x0 (file)
DEBUG:perf:    match: ran 1.04 seconds on 'reference DNS over HTTPS endpoints' for 0x0 (file)
DEBUG:perf:    match: ran 0.57 seconds on 'reference anti-VM strings targeting VirtualBox' for 0x0 (file)
```

## functions
The slow functions are all massive, e.g. 0x4149c0 🤢 
![2021-06-09_13-03-37](https://user-images.githubusercontent.com/17606537/121343613-2f53ee00-c923-11eb-9fb1-e28c8ea7278b.png)

or 0x41710e 🙊 
![2021-06-09_13-05-55](https://user-images.githubusercontent.com/17606537/121343955-8063e200-c923-11eb-9529-765ce6b5c9a8.png)

In addition to pre-processing rules we could introduce some heuristics to avoid at least some of these super large functions.

## rules
The slow file scope `reference...` rules all contain many regexes (as expected this is slow).

**Comment by williballenthin** [comment]
for performance profiling inputs, I recommend using [kernel32.dll](https://github.com/mandiant/capa-testfiles/blob/master/kernel32.dll_) (big) and [PMA 01-01.dll](https://github.com/mandiant/capa-testfiles/blob/master/Practical%20Malware%20Analysis%20Lab%2001-01.dll_) (small).

**Comment by williballenthin** [comment]
i'm working on the branch https://github.com/mandiant/capa/tree/profiling

**Comment by williballenthin** [comment]
many matching enhancements were merged in v3. if there are new ideas for optimizations, please open new issues.
