### ISSUE TITLE
Build for aarch64 ARM architecture

### ISSUE THREAD

**Issue by Harri-Renney** [mandiant/capa#683]
### Description

I am having issues building the binary program on an Linux ARM device using aarch64 achitecture (A jetson nano). It seems like there is an error during the installation process when executing `pip install -e /local/path/to/src`. It appears that there is no distribution of python-flirt for aarch64 as the following error is output:

```
ERROR: Could not find a version that satisfies the requirement python-flirt==0.6.3; extra == "flirt" (from viv-utils[flirt]) (from versions: none)
ERROR: No matching distribution found for python-flirt==0.6.3; extra == "flirt"
```

Any help or just an idea where to start looking to build CAPA for ARM would be great.

**Expected behavior:**

The program is built and the binaries generated to run the program on the Jetson Nano ARM device.

**Actual behavior:**

Build fails and cannot find python-flirt.

### Versions

CAPA version 2.0.0

**Comment by Harri-Renney** [comment]
Hi,

I've managed to get a build for the aarch64 following the tools your reference led me to. When generated, it is titled:
```
python_flirt-0.6.5-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
```

This has enabled me to run CAPA and FLOSS. Let me know if this build would be useful for you and you'd like these files.

**Comment by williballenthin** [comment]
that would be very helpful @Harri-Renney! would you please share the steps you took?

**Comment by Harri-Renney** [comment]
@williballenthin 

1. Install the maturin PyO3 tool: ```pip install maturin``` This tool can be used to generate Python bindings for correctly configured Rust projects.
2. Download the lancelot project from git: ```git clone https://github.com/williballenthin/lancelot``` This project contains FLIRT and the configuration for generating python bindings.
3. Navigate into the pyflirt directory inside the project: ```cd lancelot/pyflirt```
4. Use the maturin tool to generate Python bindings for FLIRT: ```git maturin build --release```
5. Navigate into the directory where the wheel distribution build has been generated: ```git cd ../target/wheels```
6. Install the distribution file that has been generated for the platform you have built it on: ```pip install [your_platform_specific_name].wheel```
7. You have now built and installed python-flirt on your system. You can now get the source code for projects like CAPA and FLOSS and install them without the installation process being halted by the missing python-flirt distribution. You may need to uncomment the line "viv-utils[flirt]==0.6.5" inside the setup.py file inside projects that try to install python-flirt to stop them searching for it and just use your version already installed.

**Comment by williballenthin** [comment]
ah, ok, thanks!

it looks like you went through all the build steps on your aarch64 device. i'm glad to see they worked and that demonstrates that its possible to prepare builds for that architecture.

since none of us own nor work with aarch64 devices, we'll have to see if we can configure cross compilation by rust/cargo/maturin to aarch64 from x86. in theory this is possible.
