### ISSUE TITLE
redirect print for tqdm

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#749]
see `redirecting_print_to_tqdm` in `lint.py`

_Originally posted by @mr-tz in https://github.com/fireeye/capa/pull/747#discussion_r698317172_

**Comment by mr-tz** [comment]
I'd say we move it to `capa\helpers.py` or similar.

**Comment by Aayush-Goel-04** [comment]
> I'd say we move it to `capa\helpers.py` or similar.

Will start working on it.
- Create redirect function in `capa\helpers.py.`
- Make changes to capa main
