### ISSUE TITLE
Better Documentation On Rule Version Compatibility

### ISSUE THREAD

**Issue by myrtus0x0** [mandiant/capa#764]
Currently, if one were to use the current release of CAPA and the latest ruleset of https://github.com/fireeye/capa-rules errors will occur due to the rules being set for a future version of CAPA. Below is an example of running CAPA with the latest version of the ruleset. 
<img width="1679" alt="Screen Shot 2021-09-07 at 7 03 48 PM" src="https://user-images.githubusercontent.com/48422337/132438562-7a3f8198-b57f-445d-8fbd-b0fb3dfc76ce.png">

I was not able to figure this out on my own, and only through messaging @williballenthin was I able to figure out this was the issue. Documentation showing that currently the two are incompatible would be greatly appreciated!

**Comment by mr-tz** [comment]
Yes, sorry for the confusion. With (breaking) changes to the rule format there should be an according capa release.

**Comment by farjasju** [comment]
I have a similar error using `flare-capa-3.2.0` with the cloned `capa-rules` repo (`ERROR:capa:invalid rule: capa-rules/anti-analysis/anti-disasm/64-bit-execution-via-heavens-gate.yml: invalid rule: unexpected statement: instruction`).
What should I do to make it work? Checkout to a specific commit in `capa-rules`? Thanks
