### ISSUE TITLE
Capa says sample doesn't target a valid OS for ELF

### ISSUE THREAD

**Issue by ramen0x3f** [mandiant/capa#778]
### Description
When executing capa with an ELF format, I get an exception that the sample doesn't target a valid OS. (This does not happen for all ELF samples.)

### Steps to Reproduce
The legit signed ELF file [db9dfcd840ee4acc2b8b95a70a03de03](https://www.virustotal.com/gui/file/6920d34c1cbd38d68f08b9b9e1cb4501d010c672efe3f75908f1b787a784bc6f/details) demonstrates this issue. 

"File" output for this ELF is: `ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=10446551c3faa236f4afb975e581095152bb5a28, stripped`

Reproduce with: `capa ./db9dfcd840ee4acc2b8b95a70a03de03 --format elf`

**Expected behavior:**
This should launch capa and match rules like normal. 

**Actual behavior:**
The capa command will produce the below:
```
Traceback (most recent call last):
  File "/home/user/envs/malware/bin/capa", line 11, in <module>
    load_entry_point('flare-capa', 'console_scripts', 'capa')()
  File "/home/user/tools/github/capa/capa/main.py", line 987, in main
    extractor = get_extractor(
  File "/home/user/tools/github/capa/capa/main.py", line 510, in get_extractor
    if not is_supported_os(path):
  File "/home/user/tools/github/capa/capa/main.py", line 283, in is_supported_os
    return len(list(capa.features.extractors.common.extract_os(buf))) == 1
  File "/home/user/tools/github/capa/capa/features/extractors/common.py", line 65, in extract_os
    yield OS(os), 0x0
  File "/home/user/tools/github/capa/capa/features/common.py", line 290, in __init__
    assert value in (VALID_OS)
AssertionError
```

### Versions
capa 2.0.0, standalone. Running on Kali linux in a Python virtual environment.

**Comment by williballenthin** [comment]
would you please try again using the v3 released this morning? there were some fixes in the past couple days to address this sort of exception

**Comment by williballenthin** [comment]
as mentioned above, `file` indicates: `ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=10446551c3faa236f4afb975e581095152bb5a28, stripped`

note that this doesn't have an associated OS, it just says it supports SYSV on x64.

`readelf` shows:

```
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
```
which is probably where `file` made its decision.

theres a reference to `libselinux.so.1`:

```
 0x0000000000000001 (NEEDED)             Shared library: [libselinux.so.1]
```

there are GNU notes that indicate versions and ABIs but don't specificially tag linux:

```
Version needs section '.gnu.version_r' contains 4 entries:
 Addr: 0x0000000000001928  Offset: 0x001928  Link: 5 (.dynstr)
  000000: Version: 1  File: libcrypt.so.1  Cnt: 1
  0x0010:   Name: GLIBC_2.2.5  Flags: none  Version: 8
  0x0020: Version: 1  File: libnsl.so.1  Cnt: 1
  0x0030:   Name: GLIBC_2.2.5  Flags: none  Version: 5
  0x0040: Version: 1  File: libpam.so.0  Cnt: 3
  0x0050:   Name: LIBPAM_EXTENSION_1.0  Flags: none  Version: 7
  0x0060:   Name: LIBPAM_1.0  Flags: none  Version: 6
  0x0070:   Name: LIBPAM_MODUTIL_1.0  Flags: none  Version: 4
  0x0080: Version: 1  File: libc.so.6  Cnt: 6
  0x0090:   Name: GLIBC_2.3  Flags: none  Version: 12
  0x00a0:   Name: GLIBC_2.14  Flags: none  Version: 11
  0x00b0:   Name: GLIBC_2.8  Flags: none  Version: 10
  0x00c0:   Name: GLIBC_2.4  Flags: none  Version: 9
  0x00d0:   Name: GLIBC_2.2.5  Flags: none  Version: 3
  0x00e0:   Name: GLIBC_2.3.4  Flags: none  Version: 2

Displaying notes found in: .note.gnu.build-id
  Owner                Data size        Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 10446551c3faa236f4afb975e581095152bb5a28
```

overall, this file is *probably* for linux (due to `libselinux`) but the ELF file doesn't really specify. so, i think capa is behaving as intended. if you can show a way to identify this file as targeting linux, then we can update capa with that technique.
