### ISSUE TITLE
short circuit evaluation of logic statements

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#824]
As discovered in [discussion/Query optimizer](https://github.com/mandiant/capa/discussions/821#discussioncomment-1595950), our rule engine thoroughly evaluates all logic nodes, including *all* children of `and`/`or`/`some` nodes. For example, when evaluating an `and` node, all of the children are evaluated, even if the first child is not satisfied.

To improve performance of the engine, we can short circuit when we know a node will not be satisfied (alt: when we know it is guaranteed to be satisfied, e.g. first child of an `or` node is satisfied).

Note, this *can* change the output of capa in `-vv` mode or the IDA plugin in limited scenarios. My intuition is that matters for the following scenario:
  - `or` node, 2+ children, such as `or: [api1, api2]`
  - both API features are present

Here, the engine will notice that `api1` is present and the `or` is satisfied, so it won't even look for `api2`. Therefore, it won't display that `api2` is related to the capability. This does *not* change which capabilities are detected, but reduces the "coverage" of features that get associated with capabilities.

Discussion: do we care about this change in display?

Note, we could always do the "fast" strategy first, and if the full rule matches, then go back and do a "thorough" evaluation.

**Comment by mr-tz** [comment]
> Note, we could always do the "fast" strategy first, and if the full rule matches, then go back and do a "thorough" evaluation.

Yes, ideally, we do this to show *all* relevant code parts. If it's a big hassle, the performance gain is more important though.
