### ISSUE TITLE
use assert_never to help typecheck switch/case

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#835]
https://hakibenita.com/python-mypy-exhaustive-checking

use `assert_never` in places like this: https://github.com/mandiant/capa/blob/b9f1fe56c8c6d6a881bb9bb34d0c5ea7dedbcdd3/capa/rules.py#L1093

**Comment by cl3o** [comment]
Could I try doing this?

**Comment by williballenthin** [comment]
Absolutely! Please give it a shot and we’ll happy to review any proposed changes. I don’t think there will be any functional changes but using this construct may prevent future bugs if we introduce new enum members. I’d recommend testing with mypy before and after to make sure there are no surprises. 

Thank you!

**Comment by cl3o** [comment]
Great! I've begun working on it now. Would you want me to also refactor some of the string arguments into Literals? For example in get_workspace(path, format, sigpaths) - the format argument could be represented using a Literal so using assert_never is possible there as well? i.e `Format = Literal['auto', 'pe', 'elf', 'sc32', 'sc64']` 
Sorry if I explain things a bit unclearly. I'm pretty new when it comes to contributing to open-source projects.
Thank you.

**Comment by williballenthin** [comment]
closed in #839 by @cl3o
