### ISSUE TITLE
capa explorer install note: $IDAUSR/plugins

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#892]
add note of `$IDAUSR/plugins` as per https://hex-rays.com/blog/igors-tip-of-the-week-33-idas-user-directory-idausr/

**Comment by williballenthin** [comment]
there is nice text here describing such an installation process: https://github.com/gaasedelen/lighthouse#ida-installation

![image](https://user-images.githubusercontent.com/156560/197764767-52e82937-fd76-48f6-95ad-a4c76c176c7b.png)
