### ISSUE TITLE
IDA plugin: ELF file format error

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#911]
CC: @mike-hunhoff 

Are ELF files properly enabled in the IDA plugin?

```
ERROR:capa.ida.plugin.form:Failed to extract capabilities from database (error: ('file format: %s', 'ELF for Intel 386 (Executable)'))
INFO:capa.ida.plugin.form:Analysis failed.
```

**Comment by mr-tz** [comment]
related: #910

**Comment by mike-hunhoff** [comment]
@mr-tz looks like a bug introduced here:

https://github.com/mandiant/capa/blob/b4a239569c9edf2da3789b6da578cd316c67da51/capa/features/extractors/ida/file.py#L157-L167

I'll take a closer look and push out a fix. Thanks for reporting!

**Comment by williballenthin** [comment]
im not quite sure how to enumerate all of the formats, though I think this is the source of the format above:

![image](https://user-images.githubusercontent.com/156560/159311936-cabe7910-2a9c-43a3-8106-9007cb67f028.png)

![image](https://user-images.githubusercontent.com/156560/159312011-defeac31-3625-4583-93c2-0afd2ddd998d.png)


so maybe we can get away with checking for `format_name.startswith("ELF for")`

**Comment by mike-hunhoff** [comment]
so we use the following for other file format checks:

https://github.com/mandiant/capa/blob/1b2f0fc85dcfc968e7bac8e09d1175204b688794/capa/ida/helpers.py#L24-L30

+

https://github.com/mandiant/capa/blob/1b2f0fc85dcfc968e7bac8e09d1175204b688794/capa/ida/helpers.py#L50-L62

I believe the above works for all cases

**Comment by mike-hunhoff** [comment]
so we use the following for other file format checks:

https://github.com/mandiant/capa/blob/1b2f0fc85dcfc968e7bac8e09d1175204b688794/capa/ida/helpers.py#L24-L30

+

https://github.com/mandiant/capa/blob/1b2f0fc85dcfc968e7bac8e09d1175204b688794/capa/ida/helpers.py#L50-L62

I believe the above works for all cases

**Comment by mike-hunhoff** [comment]
let me see if I can grab the MD5 from @mr-tz to double-check.
