### ISSUE TITLE
parse constants from lea instruction as both number and offset features

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#925]
we often see the `lea` instruction used for arithmetic e.g.

`lea     eax, [eax+61C88647h]`

where in the above example `0x61C88647` is a magic value used in the tiny encryption algorithm (TEA).

Currently we parse `0x61C88647` as an `offset` feature but ideally we would also parse the value as a `number` feature to allow more concise rule writing. Parsing as both `offset` and `number` features would only apply to `lea` instructions.

Pros:
- more concise rules for situations where `lea` is used for arithmetic

Cons:
- we potentially generate many additional `number` features

**Comment by mr-tz** [comment]
dup of #320 😄

**Comment by williballenthin** [comment]
test rule `get process heap flags`

**Comment by williballenthin** [comment]
also maybe extract offsets from numbers like `add ???, <number>` when number is reasonable small

**Comment by williballenthin** [comment]
e.g. 

<img width="267" alt="image" src="https://user-images.githubusercontent.com/156560/161816787-f5eb5359-614a-4344-8760-0a0604a6f7cb.png">
