### ISSUE TITLE
CI: build fails - PyInstaller issue?

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#936]
```
...
   ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

see for example https://github.com/mandiant/capa/actions/runs/2090953281

**Comment by williballenthin** [comment]
https://github.com/pyinstaller/pyinstaller/issues/6704

**Comment by williballenthin** [comment]
i guess we don't get dependabot notices because pyinstaller is not listed in our deps. perhaps we should add pyinstaller to `[dev]` dependencies?

**Comment by williballenthin** [comment]
we can at least install pyinstaller successfully now: https://github.com/mandiant/capa/runs/5857908266?check_suite_focus=true

**Comment by mr-tz** [comment]
thank you!
