### ISSUE TITLE
dotnet: emit feature VA or file offset?

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#954]
we emit the VA of features in our other extractors but I think emitting the file offset for .NET features better suits our user's needs. we also see tools like dnspy use file offset in IL mode.

we need to document this difference if we decide to move forward with emitting the file offset.

**Comment by williballenthin** [comment]
i think other tools emit VA (not RVA, nit).

emitting file offset for .NET sounds reasonable. though, what happens if have both native and .NET features? guess we should wait and see.

does .NET not have a concept of VA?

**Comment by mr-tz** [comment]
should we additionally emit the token?

**Comment by mike-hunhoff** [comment]
I like this breakdown:

- File scope - emit tokens
- Function scope - emit tokens + file offset
- Instructions - emit file offset (we don't have tokens to associate with individual instructions)

**Comment by williballenthin** [comment]
for instructions, does it make more sense to emit token + RVA?

im trying to think about how a user would make use of these locations/addresses. i dont recall how to use file offset for .NET analysis, though with the token i'd know how to navigate to the method in dnspy and then review the instruction via RVA.

**Comment by williballenthin** [comment]
in #981 we use the metadata token + the RVA
