### ISSUE TITLE
naming: dotnet, dn, .net, etc.

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#956]
let's try to be consistent with naming

use `dn` prefix throughout?

```suggestion
class DnfileFeatureExtractor(FeatureExtractor):
```

??? up for discussion

_Originally posted by @williballenthin in https://github.com/mandiant/capa/pull/955#discussion_r842125380_

**Comment by williballenthin** [comment]
yeah, i think this is good, when reasonable. for example, lets keep `is_dotnet_file` (not `is_dn_file`), but i do like `DnfileExtractor` over `DotnetfileExtractor`

**Comment by mike-hunhoff** [comment]
same thoughts; dn over dotnet when possible

**Comment by mr-tz** [comment]
👍  see e.g. 1418562b
