### ISSUE TITLE
dotnet: API name manipulation does not play well w/ dotnet names

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#957]
e.g. `System.IO.Path::GetFileName` emitted as `system.io.Path::GetFileName`

https://github.com/mandiant/capa/blob/df03932f89b0476a79e7b120369cb2a6b5e9e516/capa/features/insn.py#L14-L21

**Comment by mr-tz** [comment]
Can we always assume there are `::`? Then, handle that differently? Or we create a new subclass.
